### ISSUE TITLE
c2cgeoportal 1.5.1 - startup error in Apache

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1133]
When running c2cgeoportal 1.5.1 through Apache, I get a blocking error.

It looks like `from zc.buildout.buildout import Buildout` throws a fatal error, thus any call to the app returns an error 500

Am I the only one having this issue ?

I modified line https://github.com/camptocamp/c2cgeoportal/blob/1.5/c2cgeoportal/scripts/c2ctool.py#L41 to
```
try:
    from zc.buildout.buildout import Buildout
except:
    pass
```
just in order to make it work... What's the point of this `c2ctool.py` file ? It seems this file is quite problematic for SITN...

```
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48] mod_wsgi (pid=6692): Target WSGI script 'D:/Applications/Mapfish/sitn_internet/buildout/parts/modwsgi/wsgi' cannot be loaded as Python module.
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48] mod_wsgi (pid=6692): Exception occurred processing WSGI script 'D:/Applications/Mapfish/sitn_internet/buildout/parts/modwsgi/wsgi'.
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48] Traceback (most recent call last):
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "D:/Applications/Mapfish/sitn_internet/buildout/parts/modwsgi/wsgi", line 120, in <module>
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     application = loadapp("config:" + configfile, name=None)
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\pastedeploy-1.5.0-py2.6.egg\\paste\\deploy\\loadwsgi.py", line 247, in loadapp
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     return loadobj(APP, uri, name=name, **kw)
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\pastedeploy-1.5.0-py2.6.egg\\paste\\deploy\\loadwsgi.py", line 272, in loadobj
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     return context.create()
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\pastedeploy-1.5.0-py2.6.egg\\paste\\deploy\\loadwsgi.py", line 710, in create
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     return self.object_type.invoke(self)
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\pastedeploy-1.5.0-py2.6.egg\\paste\\deploy\\loadwsgi.py", line 203, in invoke
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     app = context.app_context.create()
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\pastedeploy-1.5.0-py2.6.egg\\paste\\deploy\\loadwsgi.py", line 710, in create
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     return self.object_type.invoke(self)
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\pastedeploy-1.5.0-py2.6.egg\\paste\\deploy\\loadwsgi.py", line 146, in invoke
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\pastedeploy-1.5.0-py2.6.egg\\paste\\deploy\\util.py", line 56, in fix_call
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     val = callable(*args, **kw)
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\sitn\\__init__.py", line 58, in main
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     config.include('c2cgeoportal')
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\pyramid-1.5.1-py2.6.egg\\pyramid\\config\\__init__.py", line 755, in include
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     c(configurator)
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\c2cgeoportal_win-1.5.1-py2.6.egg\\c2cgeoportal\\__init__.py", line 348, in includeme
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     config.scan(ignore='c2cgeoportal.tests')
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\pyramid-1.5.1-py2.6.egg\\pyramid\\config\\__init__.py", line 930, in scan
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     ignore=ignore)
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\venusian-1.0a8-py2.6.egg\\venusian\\__init__.py", line 199, in scan
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     __import__(modname)
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\c2cgeoportal_win-1.5.1-py2.6.egg\\c2cgeoportal\\scripts\\c2ctool.py", line 41, in <module>
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     from zc.buildout.buildout import Buildout
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\zc.buildout-1.5.2-py2.6.egg\\zc\\buildout\\buildout.py", line 56, in <module>
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     zc.buildout.easy_install._has_broken_dash_S(sys.executable))
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\sitn_internet\\buildout\\eggs\\zc.buildout-1.5.2-py2.6.egg\\zc\\buildout\\easy_install.py", line 103, in _has_broken_dash_S
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48]     return bool(int(stdout.strip()))
[Tue Nov 11 08:32:37 2014] [error] [client 148.196.31.48] ValueError: invalid literal for int() with base 10: ''
```

**Comment by sbrunner** [comment]
Is this issue still relevant ?

**Comment by kalbermattenm** [comment]
Yes it is....
