### ISSUE TITLE
buildout error in 1.5.2 tag

### ISSUE THREAD

**Issue by arnaud-morvan** [camptocamp/c2cgeoportal#1220]
I've meet an error when creating a new portal from scratch with 1.5.2 tag
(works well with 1.5 branch)
maybe it would be good to have a test to verify that this works before releasing new versions ?

```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/amorvan/c2cgeoportal/buildout/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 1805, in main
    getattr(buildout, command)(args)
  File "/home/amorvan/c2cgeoportal/buildout/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 425, in install
    self._load_extensions()
  File "/home/amorvan/c2cgeoportal/buildout/eggs/zc.buildout-1.5.2-py2.7.egg/zc/buildout/buildout.py", line 989, in _load_extensions
    ep.load()(self)
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1991, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/amorvan/c2cgeoportal/buildout/eggs/lovely.buildouthttp-0.6.1-py2.7.egg/lovely/buildouthttp/buildouthttp.py", line 18, in <module>
    from six.moves.urllib import request as urllib_request
ImportError: No module named urllib

**Comment by sbrunner** [comment]
already fixed
