### ISSUE TITLE
c2cgeoportal.views.proxy - AssertionError: keep-alive is a "hop-by-hop"

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1394]
Since I upgraded to 1.6.0rc1, I cannot request any mapserver layer. It looks like Waitress doesn't like something in the headers (see stack trace hereunder).

From what I can see, the request is sent to mapserver, but the response of the first URL hereunder is an error 500.

Am I the only one having this issue ?

```
2015-06-08 16:18:23,364 INFO  [c2cgeoportal.views.proxy][Dummy-5] Send query to URL:
http://localhost/michael/mapserv?LAYERS=poi_dechet&STYLES=&WIDTH=2420&SERVICE=WMS&cache_version=3f49fab67ed24f62bd5680c4
941b8e3b&FORMAT=image%2Fpng&REQUEST=GetMap&HEIGHT=1471&SRS=EPSG%3A21781&VERSION=1.1.1&BBOX=424370%2C131030%2C666320%2C27
8180&TRANSPARENT=TRUE.
2015-06-08 16:13:07,101 ERROR [waitress][Dummy-3] Exception when serving /mapserv_proxy
Traceback (most recent call last):
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\waitress\channel.py", line 337, in service
    task.service()
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\waitress\task.py", line 173, in service
    self.execute()
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\waitress\task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\weberror\evalexception.py", line 235, in __call_
_
    return self.respond(environ, start_response)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\weberror\evalexception.py", line 459, in respond

    exc_info)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\waitress\task.py", line 354, in start_response
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\weberror\evalexception.py", line 431, in respond

    app_iter = self.application(environ, detect_start_response)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\fanstatic\publisher.py", line 219, in __call__
    return self.app(environ, start_response)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\fanstatic\injector.py", line 61, in __call__
    return response(environ, start_response)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\webob\response.py", line 1021, in __call__
    start_response(self.status, headerlist)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\weberror\evalexception.py", line 424, in detect_
start_response
    return start_response(status, headers, exc_info)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\waitress\task.py", line 384, in start_response
    'a WSGI application (see PEP 3333)' % k)
AssertionError: keep-alive is a "hop-by-hop" header; it cannot be used by a WSGI application (see PEP 3333)
```

**Comment by kalbermattenm** [comment]
Thanks @sbrunner ;-)
