### ISSUE TITLE
[Upgrade to 1.6] Issue with version_params

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1524]
If I apply #1521, I have this python error:

````
MakoRenderingException: Traceback (most recent call last):
    File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__ result = template.render_unicode(**system)
    File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode as_unicode=True)
    File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render **_kwargs_for_callable(callable_, data))
    File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
    File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template callable_(context, *args, **kwargs)
    File "/var/www/vhosts/nyon-geoportail/private/dev/nyon/templates/viewer.js", line 73, in render_body return url + "?${'&'.join(["%s=%s" % p for p in version_params.items()]) | n}"; AttributeError: 'Undefined' object has no attribute 'items'
````

Did I missed something?

**Comment by sbrunner** [comment]
Fixed with  #1481 (in 1.6.2)
