### ISSUE TITLE
[Upgrade to 1.6] Error with print v2 capabilities

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1545]
After upgrade to 1.6, the print checker throw an error:

````
[Tue Aug 25 12:23:01.313829 2015] [wsgi:error] [pid 16358] 2015-08-25 12:23:01,313 ERROR [c2cgeoportal.views.proxy][Dummy-5] Error 'Not Found' in response of URL:
[Tue Aug 25 12:23:01.313855 2015] [wsgi:error] [pid 16358] http://localhost:8080/print-dev/print/nyon/capabilities.json?cache_version=cc0b823a444240a1b1476a36fdc33327.
````

HTML file:

````
HTTP Status 404 - /print-dev/print/nyon/capabilities.json
type Status report
message /print-dev/print/nyon/capabilities.json
description The requested resource is not available.
Apache Tomcat/8.0.14 (Debian)
````

Maybe I missed something in the upgrade process? I just defined print_version to 2 in my makefile.

**Comment by sbrunner** [comment]
It's not clearly documented but you should have this config in your vars file to use the print v2
`print_url: http://localhost:8080/print-{instanceid}/pdf/`

**Comment by rbovard** [comment]
Different but not better:

````
[Tue Aug 25 13:57:49.141295 2015] [wsgi:error] [pid 26442] 2015-08-25 13:57:49,141 INFO  [c2cgeoportal.views.checker][Dummy-3] Checker for url: http://nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net/dev/wsgi/printproxy/capabilities.json?cache_version=5231b7171b9540ab884e30c2e29b255f
[Tue Aug 25 13:57:49.150871 2015] [wsgi:error] [pid 26442] 2015-08-25 13:57:49,150 INFO  [c2cgeoportal.views.proxy][Dummy-2] Send query to URL:
[Tue Aug 25 13:57:49.151064 2015] [wsgi:error] [pid 26442] http://localhost:8080/print-dev/pdf/capabilities.json?cache_version=5231b7171b9540ab884e30c2e29b255f.
[Tue Aug 25 13:57:49.155903 2015] [wsgi:error] [pid 26442] 2015-08-25 13:57:49,155 ERROR [c2cgeoportal.views.proxy][Dummy-2] Error 'Not Found' in response of URL:
[Tue Aug 25 13:57:49.155933 2015] [wsgi:error] [pid 26442] http://localhost:8080/print-dev/pdf/capabilities.json?cache_version=5231b7171b9540ab884e30c2e29b255f.
[Tue Aug 25 13:57:49.156070 2015] [wsgi:error] [pid 26442] 2015-08-25 13:57:49,155 ERROR [c2cgeoportal.views.proxy][Dummy-2] Status: 404
[Tue Aug 25 13:57:49.156218 2015] [wsgi:error] [pid 26442] 2015-08-25 13:57:49,156 ERROR [c2cgeoportal.views.proxy][Dummy-2] Method: GET
[Tue Aug 25 13:57:49.156361 2015] [wsgi:error] [pid 26442] 2015-08-25 13:57:49,156 ERROR [c2cgeoportal.views.proxy][Dummy-2] --- With headers ---
[Tue Aug 25 13:57:49.156388 2015] [wsgi:error] [pid 26442] Host: nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net
[Tue Aug 25 13:57:49.156406 2015] [wsgi:error] [pid 26442] Cache-Control: no-cache
[Tue Aug 25 13:57:49.156415 2015] [wsgi:error] [pid 26442] Accept-Encoding: gzip, deflate
[Tue Aug 25 13:57:49.156420 2015] [wsgi:error] [pid 26442] User-Agent: Python-httplib2/0.9 (gzip)
[Tue Aug 25 13:57:49.156542 2015] [wsgi:error] [pid 26442] 2015-08-25 13:57:49,156 ERROR [c2cgeoportal.views.proxy][Dummy-2] --- Return content ---
[Tue Aug 25 13:57:49.156678 2015] [wsgi:error] [pid 26442] 2015-08-25 13:57:49,156 ERROR [c2cgeoportal.views.proxy][Dummy-2] Error while generating PDF:
[Tue Aug 25 13:57:49.156704 2015] [wsgi:error] [pid 26442] Unknown method: /capabilities.json
````

**Comment by sbrunner** [comment]
You shouldn't have any `capabilities.json` in the logs if you configure the client to use the print v2 ...
and you miss the end slash ...

**Comment by rbovard** [comment]
With `print_url: http://localhost:8080/print-{instanceid}/pdf/` I have in the log `http://localhost:8080/print-dev/pdf//capabilities.json` it's the reason why I removed it in first time...

````

[Tue Aug 25 15:12:19.536540 2015] [wsgi:error] [pid 32315] 2015-08-25 15:12:19,536 INFO  [c2cgeoportal.views.checker][Dummy-5] Checker for url: http://nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net/dev/wsgi/printproxy/capabilities.json?cache_version=40802c8f00c64cba8d379be8142fdd6c
[Tue Aug 25 15:12:19.547876 2015] [wsgi:error] [pid 32315] 2015-08-25 15:12:19,547 INFO  [c2cgeoportal.views.proxy][Dummy-8] Send query to URL:
[Tue Aug 25 15:12:19.548007 2015] [wsgi:error] [pid 32315] http://localhost:8080/print-dev/pdf//capabilities.json?cache_version=40802c8f00c64cba8d379be8142fdd6c.
[Tue Aug 25 15:12:19.555135 2015] [wsgi:error] [pid 32315] 2015-08-25 15:12:19,554 ERROR [c2cgeoportal.views.proxy][Dummy-8] Error 'Not Found' in response of URL:
[Tue Aug 25 15:12:19.555323 2015] [wsgi:error] [pid 32315] http://localhost:8080/print-dev/pdf//capabilities.json?cache_version=40802c8f00c64cba8d379be8142fdd6c.
[Tue Aug 25 15:12:19.555703 2015] [wsgi:error] [pid 32315] 2015-08-25 15:12:19,555 ERROR [c2cgeoportal.views.proxy][Dummy-8] Status: 404
[Tue Aug 25 15:12:19.556120 2015] [wsgi:error] [pid 32315] 2015-08-25 15:12:19,555 ERROR [c2cgeoportal.views.proxy][Dummy-8] Method: GET
[Tue Aug 25 15:12:19.556507 2015] [wsgi:error] [pid 32315] 2015-08-25 15:12:19,556 ERROR [c2cgeoportal.views.proxy][Dummy-8] --- With headers ---
[Tue Aug 25 15:12:19.556629 2015] [wsgi:error] [pid 32315] Host: nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net
[Tue Aug 25 15:12:19.558113 2015] [wsgi:error] [pid 32315] Cache-Control: no-cache
[Tue Aug 25 15:12:19.558265 2015] [wsgi:error] [pid 32315] Accept-Encoding: gzip, deflate
[Tue Aug 25 15:12:19.558291 2015] [wsgi:error] [pid 32315] User-Agent: Python-httplib2/0.9 (gzip)
[Tue Aug 25 15:12:19.558603 2015] [wsgi:error] [pid 32315] 2015-08-25 15:12:19,558 ERROR [c2cgeoportal.views.proxy][Dummy-8] --- Return content ---
[Tue Aug 25 15:12:19.558989 2015] [wsgi:error] [pid 32315] 2015-08-25 15:12:19,558 ERROR [c2cgeoportal.views.proxy][Dummy-8] Error while generating PDF:
[Tue Aug 25 15:12:19.559107 2015] [wsgi:error] [pid 32315] Unknown method: /capabilities.json
````

To use print v2, I put `PRINT_VERSION = 2` in my `nyon.mk`, anything else to do?

**Comment by sbrunner** [comment]
I don't see that your in the checkers ...
Then you should configure it like this:
```
vars:
    ...
    check_collector:
        disabled: [checker_print3capabilities, checker_pdf3]

update_paths:
...
- check_collector
```

All previous changes are useful to make the print working :-)

**Comment by rbovard** [comment]
With the changes you preconised, i have no more checks...

`Elapsed all: 0.0000`

**Comment by rbovard** [comment]
> All previous changes are useful to make the print working :-)

BTW the print is still not working

The changes I've made:

````
 vars:
+    print_url: http://localhost:8080/print-{instanceid}/pdf/

     check_collector:
         ...
+        disabled: [checker_print3capabilities, checker_pdf3]

 update_paths:
...
-- check_collector.hosts
+- check_collector

````

**Comment by sbrunner** [comment]
I don't see that you already have an `update_paths` to `check_collector.hosts`, re add the `.hosts` to have some check again :-)

**Comment by rbovard** [comment]
Ok thanks, it works fine > there is no more failure with print test because it's removed.

But the print is still not working (no infos in Apache logs)...

**Comment by sbrunner** [comment]
The print v3 is removed, the print v2 should be tested ...

**Comment by sbrunner** [comment]
In the `/srv/tomcat/tomcat1/logs/mapfish-print.log` I have some error like:
`attribute [spec.pages[0].mapTitle] missing`
`spec.layers[0].baseURL has an invalid value: http://ows.asitvd.ch/wmts/ (spec.layers[0].baseURL has an invalid value: http://ows.asitvd.ch/wmts/)`
...

**Comment by sbrunner** [comment]
Effectively the print v2 is disable because you add `- check_collector.disabled` in the `update_paths:`, it should be overwritten not updated ...

**Comment by rbovard** [comment]
> it should be overwritten not updated ...

How do I do that?

**Comment by rbovard** [comment]
> I have some error like...

Ok, I see them now (there was a JS issue before with legend panel).

`org.mapfish.print.InvalidJsonValueException: spec.layers[0].baseURL has an invalid value: http://ows.asitvd.ch/wmts/`

It was working fine on 1.5, should I need to edit something now?

**Comment by sbrunner** [comment]
> How do I do that? (I just want to test print v2 instead of v3)

By default the checker will be disable for the checker v2:
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_vars.yaml_tmpl#L248

Then if you update it with `[checker_print3capabilities, checker_pdf3]` you will get `[checker_printcapabilities, checker_pdf, checker_print3capabilities, checker_pdf3]` (you can see it in the .build/config.yaml) => disable for booth. Then it should be overwritten.

**Comment by sbrunner** [comment]
For the print errors you don't have any `config.yaml` for the print ...

**Comment by sbrunner** [comment]
As I see the `print/print.mako` should be renamed to `print/config.yaml.mako` :-)

**Comment by rbovard** [comment]
Nice catch, an upgrade side effect ;)

But I still have this error:

````
Caused by: org.mapfish.print.InvalidJsonValueException: spec.layers[0].baseURL has an invalid value: http://nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net/dev/wsgi/mapserv_proxy?cache_version=b9d5df552a724e08855e9658e0a5536f
````

**Comment by sbrunner** [comment]
Strange I have the same issue on my instance, and I just rebuild the print ant no more issue ...
Then try to regenerate it:
``` bash
touch print/print-servlet-2.1-SNAPSHOT-IMG-MAGICK.war
make -f ....mk build
```

**Comment by rbovard** [comment]
Same here, very strange...

**Comment by rbovard** [comment]
> Then if you update it with [checker_print3capabilities, checker_pdf3] you will get [checker_printcapabilities, checker_pdf, checker_print3capabilities, checker_pdf3] (you can see it in the .build/config.yaml) => disable for booth. Then it should be overwritten.

@sbrunner Sorry about that question, but what's the syntax to overvrite it... ?

**Comment by sbrunner** [comment]
Not special syntax, just don't have the full path in the `update_path`.

**Comment by rbovard** [comment]
Sorry but i really don't see what to write :(

For now I removed v3 checks with:

````
     check_collector:
         hosts: []
+        disabled: [checker_print3capabilities, checker_pdf3]

 update_paths:
 - authtkt
 - checker
 - check_collector.hosts
+- check_collector.disabled
````

And I just want to readd v2 checks.

**Comment by sbrunner** [comment]
Than it should be:

````
     check_collector:
         hosts: []
+        disabled: [checker_print3capabilities, checker_pdf3]

 update_paths:
 - authtkt
 - checker
 - check_collector.hosts
 - check_collector.disabled
````

**Comment by rbovard** [comment]
Oh thanks, I finally got my checks for v2 :)

But I have now an error with the checker `Print PDF`

````
Traceback (most recent call last)
File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
Display the sourcecode for this frameOpen an interactive python shell in this frameresult = handler(request)
File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = handler(request)
File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 94, in tm_tween
Display the sourcecode for this frameOpen an interactive python shell in this framereraise(*exc_info)
File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 75, in tm_tween
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = handler(request)
File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/pyramid/router.py", line 164, in handle_request
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = view_callable(context, request)
File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/pyramid/config/views.py", line 383, in viewresult_to_response
Display the sourcecode for this frameOpen an interactive python shell in this frameresult = view(context, request)
File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/pyramid/config/views.py", line 481, in _class_requestonly_view
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = getattr(inst, attr)()
File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/checker.py", line 126, in pdf
Display the sourcecode for this frameOpen an interactive python shell in this framereturn self.make_response(self._pdf())
File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/checker.py", line 136, in _pdf
Display the sourcecode for this frameOpen an interactive python shell in this frame"layout": self.settings["print_template"],
KeyError: 'print_template'
````

But my print works fine... :/

**Comment by sbrunner** [comment]
You miss to get the checker configuration from your old `config.yaml` file ...

**Comment by rbovard** [comment]
Hehe, thanks... It finally works !

I think you can improve the docs for print v2 and related checkers, because some other people will encounter the same issues.

**Comment by sbrunner** [comment]
I think that this issue can be closed, reopen it if you don't agree.
