### ISSUE TITLE
Upgrade 1.6.2 step 4 error

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#1567]
I get the following error (seems to be a git error) doing step 4 of upgrade to 1.6.2

dgnerre@cartoriviera3:/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish$ .build/venv/bin/c2ctool upgrade preprod.mk 1.6.2 --step 4
make: 'project.yaml' is up to date.
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 9, in <module>
    load_entry_point('c2cgeoportal==1.6.2', 'console_scripts', 'c2ctool')()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 101, in main
    c2ctool.upgrade()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 222, in upgrade
    self.step4()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 412, in step4
    check_call(["git", "commit", "-m", "Upgrade to GeoMapFish %s" % self.options.version])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'Upgrade to GeoMapFish 1.6.2']' returned non-zero exit status 1

**Comment by sbrunner** [comment]
...
nothing to commit, working directory clean
...
['git', 'commit', '-m', 'Upgrade to GeoMapFish 1.6.2']

The step 4 will commit your changes but it's looks like that you already commit them, than just ignore this error and your upgrade is finish :-)

**Comment by rbovard** [comment]
I had the same "issue", but after looking at the code of step4() I knew the upgrade was done :)

**Comment by gnerred** [comment]
Maybe C2C could put a clean message if all commits are already done... Other clients will for sure face the same problem.
