### ISSUE TITLE
CoverageException when running the unit tests

### ISSUE THREAD

**Issue by elemoine** [camptocamp/c2cgeoportal#1646]
I just tried to run the c2cgeoportal unit tests using

```
.build/venv/bin/python setup.py nosetests -a '!functional'
```

as indicated in the `server_side.html` documentation, but it fails with a CoverageException:

```
Traceback (most recent call last):
  File "setup.py", line 128, in <module>
    "geomapfish-angular = c2cgeoportal.lib.lingua_extractor:GeoMapfishAngularExtractor",
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/nose/commands.py", line 158, in run
    TestProgram(argv=argv, config=self.__config)
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/nosexcover/nosexcover.py", line 53, in configure
    super(XCoverage, self).configure(options, config)
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/nose/plugins/cover.py", line 155, in configure
    self.coverInstance.load()
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/coverage/control.py", line 657, in load
    self.data_files.read(self.data)
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/coverage/data.py", line 631, in read
    data.read_file(self.filename)
  File "/home/elemoine/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/coverage/data.py", line 293, in read_file
    filename, exc.__class__.__name__, exc,
coverage.misc.CoverageException: Couldn't read data from '/home/elemoine/c2cgeoportal/.coverage': CoverageException: Doesn't seem to be a coverage.py data file
```

Any idea?

**Comment by elemoine** [comment]
I get the same error when using `make tests`.

**Comment by elemoine** [comment]
I removed the `.coverage` file I had and I can now run the tests.

**Comment by elemoine** [comment]
I could just close this isuse, but I am  curious to know why I hit that problem.

**Comment by sbrunner** [comment]
Good question :-/

**Comment by elemoine** [comment]
Ok, let's close if you don't know what the problem is.
