### ISSUE TITLE
1.6.4 - Raster plugin

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1682]
On the production instance (1.5):
http://sitn.ne.ch/prepub/wsgi/raster?_dc=1443775681499&lon=551804&lat=198195.5

Gives me:
{"slope": 32.3, "rayglobal": 310, "raydirect": 0, "mns": 516.5, "mnt": 516.4, "raydiffus": 251}

Which is the expected response.

Now, on my 1.6.4 instance, I have quite a strange error using the raster plugin...
If I make a request through Apache like this one on the 1.6.4 instance:

http://sitn.ne.ch/prepublication16/wsgi/raster?_dc=1443776707724&lon=551750.12499878&lat=197249.99984866&layers=mnt%2Cmns%2Cslope%2Crayglobal%2Craydiffus%2Craydirect

Then I get a server error.
 In the Apache log:
```
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48] mod_wsgi (pid=7052): Exception occurred processing WSGI script 'D:/Applications/Mapfish/prepublication16/apache/application.wsgi'., referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48] Traceback (most recent call last):, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\fanstatic\\publisher.py", line 219, in __call__, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     return self.app(environ, start_response), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\fanstatic\\injector.py", line 54, in __call__, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     response = request.get_response(self.app), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\webob\\request.py", line 1320, in send, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     application, catch_exc_info=False), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\webob\\request.py", line 1284, in call_application, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     app_iter = application(self.environ, start_response), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\prepublication16\\.build\\venv\\src\\pyramid\\pyramid\\router.py", line 243, in __call__, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     response = self.invoke_subrequest(request, use_tweens=True), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\prepublication16\\.build\\venv\\src\\pyramid\\pyramid\\router.py", line 218, in invoke_subrequest, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     response = handle_request(request), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\prepublication16\\.build\\venv\\src\\pyramid\\pyramid\\tweens.py", line 21, in excview_tween, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     response = handler(request), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\pyramid_tm\\__init__.py", line 94, in tm_tween, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     reraise(*exc_info), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\pyramid_tm\\__init__.py", line 75, in tm_tween, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     response = handler(request), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\prepublication16\\.build\\venv\\src\\pyramid\\pyramid\\router.py", line 164, in handle_request, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     response = view_callable(context, request), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\prepublication16\\.build\\venv\\src\\pyramid\\pyramid\\config\\views.py", line 353, in rendered_view, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     result = view(context, request), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "d:\\applications\\mapfish\\prepublication16\\.build\\venv\\src\\pyramid\\pyramid\\config\\views.py", line 481, in _class_requestonly_view, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     response = getattr(inst, attr)(), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\c2cgeoportal\\views\\raster.py", line 70, in raster, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     rasters[ref], ref, lon, lat), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\c2cgeoportal\\views\\raster.py", line 88, in _get_raster_value, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     result = raster.get_value(lon, lat), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\c2cgeoportal\\lib\\raster\\georaster.py", line 102, in get_value, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     return tile.get_value(x, y), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]   File "D:\\Applications\\Mapfish\\prepublication16\\.build\\venv\\Lib\\site-packages\\c2cgeoportal\\lib\\raster\\georaster.py", line 55, in get_value, referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48]     file = open(self.filename, "rb"), referer: http://sitn.ne.ch/prepublication16/theme/main
[Fri Oct 02 10:59:12 2015] [error] [client 148.196.31.48] IOError: [Errno 2] No such file or directory: 'E:/data/elevation_data/pentes50cm/bt/1164313.bt', referer: http://sitn.ne.ch/prepublication16/theme/main
```
It looks like the raster plugin mixes up the path to the file it has to read. But, the paths are correctly defined in https://github.com/camptocamp/sitn_c2cgeoportal/blob/1.6/vars_sitn_internet.yaml#L31-L52 and the dbf point to the correct bt files.

If I do the same request using pserve on the same instance:
http://localhost:5000/raster?_dc=1443776707724&lon=551750.12499878&lat=197249.99984866&layers=mnt%2Cmns%2Cslope%2Crayglobal%2Craydiffus%2Craydirect
Then:
```
{"slope": 32.3, "rayglobal": 310, "raydirect": 0, "mns": 516.5, "mnt": 516.4, "raydiffus": 251}
```
Which is the expected response...

It is like the raster plugin mixes up the path to the files when requesting this route through Apache.

I really do not get why this is happening... Does anyone have any clue ???

**Comment by sbrunner** [comment]
Witch makefile do you use ?

**Comment by kalbermattenm** [comment]
https://github.com/camptocamp/sitn_c2cgeoportal/blob/1.6/nesitn5_prepublication.mk

**Comment by kalbermattenm** [comment]
This issue looks like it is resolved.... Please do not ask why... I do not know... (maybe an Apache restart, or whatever...).

I was not able to reproduce it on http://sitn.ne.ch/prepublication16/theme/main

Closing and sorry for the noise...
