### ISSUE TITLE
1.6.4 - Editing

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#1695]
Using editing in version 1.6.4, I always get the here under error when the app calls the layer ms.xsd (http://localhost:5000/layers/461/md.xsd?user=1&cache_version=425e710eb18845ec83e1cb6423b8398a - in pserve mode...)

Thus I cannot draw anything...

Moreover I am sure that my tables have a defined postgis geometry (like `POLYGON`, `LINESTRING`, etc)

The strange thing is that in the demo (http://geomapfish-demo.camptocamp.net/1.6/edit) nothing like that appears. I can not even see the md.xsd calls... The difference between the demo and our instance is that on our side the layers are not activated by default...

Did I miss something during the migration ?

```
Traceback (most recent call last):
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid_debugtoolbar\toolbar.py", line 178, in t
oolbar_tween
    response = _handler(request)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid_debugtoolbar\panels\performance.py", lin
e 71, in noresource_timer_handler
    result = handler(request)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\src\pyramid\pyramid\tweens.py", line 21, in excview_tween
    response = handler(request)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid_tm\__init__.py", line 94, in tm_tween
    reraise(*exc_info)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid_tm\__init__.py", line 75, in tm_tween
    response = handler(request)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\src\pyramid\pyramid\router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\src\pyramid\pyramid\config\views.py", line 375, in rendered_view
    context)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\src\pyramid\pyramid\renderers.py", line 417, in render_view
    return self.render_to_response(response, system, request=request)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\src\pyramid\pyramid\renderers.py", line 440, in render_to_response

    result = self.render(value, system_values, request=request)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\src\pyramid\pyramid\renderers.py", line 436, in render
    result = renderer(value, system_values)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\papyrus\renderers.py", line 178, in _render
    io = self.generator.get_class_xsd(StringIO(), cls)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\papyrus\xsd.py", line 167, in get_class_xsd
    self.add_class_properties_xsd(tb, cls)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\papyrus\xsd.py", line 151, in add_class_properti
es_xsd
    self.add_column_property_xsd(tb, p)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\papyrus\xsd.py", line 144, in add_column_propert
y_xsd
    self.add_column_xsd(tb, column, attrs)
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\papyrus\xsd.py", line 77, in add_column_xsd
    xsd_type = self.SIMPLE_GEOMETRY_XSD_TYPES[geometry_type]
KeyError: 'GEOMETRY'
```

**Comment by gnerred** [comment]
+1
I have the same error in log. I cannot see my layer in dropdown list, even if list is not gray
![edit](https://cloud.githubusercontent.com/assets/1989467/10329836/75aec84e-6cc6-11e5-97af-0d095cb6604a.png)

**Comment by ochriste** [comment]
you have to apply the modification explained in the documentation there:
http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/upgrade_application.html#edition

**Comment by kalbermattenm** [comment]
OK.... Thanks... Then a more general question.... Should we apply that on all geometries, in order to be more compliant with PostGIS 2 ?

**Comment by ochriste** [comment]
I havent widely tested that, but since it works with edition tables, I see
no reason it wouldnt work in all cases.

**Comment by kalbermattenm** [comment]
OK... I wrote a Python script which alters the geometry definition for all geometry columns in the database. 

It was quite hard to establish because I encountered a few problems...:
* The `select migrategeomtopostgis2...` query does only work on one table at time (commit in between). I do not know why... 
* The views have to be dropped, but the solution in the docs only shows how to drop and recreate them. The major problem is that special grants are lost by doing so (notably the `SELECT` grant for our favorite user...)
* If a geometry has a dimension bigger then 2, thus 3 or 4 (which actually is the case at SITN), then the `migrategeomtopostgis2` fails, thus I corrected this function.

If anyone desires to use the script, I posted it here under.

I am however not sure it will run without errors. If an errors occurs, then you might lose all our views... (thus backup the DB before running the script... NO WARRANTY from me... If you break your DB, do not blame me!!!!!

In the script I did also add the improved version of `migrategeomtopostgis2`

**Comment by kalbermattenm** [comment]
```python
# -*- coding: utf-8 -*-

# NO WARRANTY THAT IT WILL RUN WITHOUT ERRORS
# THE AUTHOR CANNOT BE HELD RESPONSIBLE FOR ANY LOST OR DAMAGE

"""
Before running this script, please create the following migration function:

CREATE OR REPLACE FUNCTION migrategeomtopostgis2(_tablename text, _geomcolumn text, _geomtype text, _srid int, _dim int) RETURNS void AS $$
DECLARE
_cleangeomtype text;
BEGIN
IF _dim = 2 THEN
    _cleangeomtype := initcap(lower(_geomtype));
ELSEIF _dim = 3 THEN
    _cleangeomtype := initcap(lower(_geomtype)) || 'Z';
ELSEIF _dim = 4 THEN
    _cleangeomtype := initcap(lower(_geomtype)) || 'ZM';
END IF;

EXECUTE ' ALTER TABLE ' || _tablename || ' ALTER COLUMN ' || _geomcolumn || ' SET DATA TYPE geometry(' || _cleangeomtype || ', ' || _srid || ')';
EXECUTE ' ALTER TABLE ' || _tablename || ' DROP CONSTRAINT IF EXISTS enforce_dims_' || _geomcolumn;
EXECUTE ' ALTER TABLE ' || _tablename || ' DROP CONSTRAINT IF EXISTS enforce_geotype_' || _geomcolumn;
EXECUTE ' ALTER TABLE ' || _tablename || ' DROP CONSTRAINT IF EXISTS enforce_srid_' || _geomcolumn;
END
$$
LANGUAGE PLPGSQL;

"""

import psycopg2

tmp_view_file = "D:/tmp/view_create.sql"

connection = psycopg2.connect(
    host="TO_BE_DEFINED",
    database="TO_BE_DEFINED",
    user="TO_BE_DEFINED",
    password="TO_BE_DEFINED",
    port=TO_BE_DEFINED
)

cursor = connection.cursor()

# 0. BE SURE TO HAVE ALL GEOMETRIES REGISTRED

sql = "SELECT Populate_Geometry_Columns(false)"
cursor.execute(sql)
connection.commit()

# 1. SELECT ALL VIEWS (avoid system & postgis views):
sql = "SELECT schemaname, viewname from pg_catalog.pg_views "
sql += "where schemaname NOT IN ('pg_catalog','information_schema') and viewname NOT IN ('raster_columns', 'raster_overviews','geography_columns','geometry_columns')"

cursor.execute(sql)

view_list = []

for row in cursor:
    view_list.append([row[0], row[1]])

# 2. GET VIEW GRANTS

view_grants = {}
for view in view_list:
    sql = "SELECT grantee, string_agg(privilege_type, ', ') AS privileges "
    sql += "FROM information_schema.role_table_grants "
    sql += "WHERE table_schema='" + view[0] + "' and table_name ='" + view[1] + "' "   
    sql += "GROUP BY grantee"

    cursor.execute(sql)

    for row in cursor:
        view_grants[view[0]+'.'+view[1]] = [row[0], row[1]]

# 3. CREATE VIEW SQL SCRIPT

sql = "copy ( select 'CREATE OR REPLACE VIEW ' || schemaname || '.' || viewname || ' AS '"
sql += "|| regexp_replace(definition,E'[\\n\\r]+', ' ', 'g') from pg_catalog.pg_views "
sql += "where schemaname NOT IN ('pg_catalog','information_schema') and "
sql += "viewname NOT IN ('raster_columns', 'raster_overviews','geography_columns','geometry_columns')) "
sql += "to '" + tmp_view_file + "'"
cursor.execute(sql)

# 4.  DROP VIEWS

for view in view_list:
    sql = "DROP VIEW " + view[0] + "." + view[1] + " CASCADE"
    try:
        cursor.execute(sql)
    except:
        pass
    connection.commit()


# 5. GET ALL GEOMETRY COLUMNS

sql = "select f_table_schema, f_table_name "
sql += "from geometry_columns"

cursor.execute(sql)

# 6. MIGRATE ALL GEOMETRY COLUMNS

cursor2 = connection.cursor()

for result in cursor:
    sql = "select migrategeomtopostgis2('\"' || f_table_schema || '\".\"' || f_table_name || '\"', f_geometry_column, type, srid, coord_dimension) "
    sql += "from geometry_columns "
    sql += "where f_table_schema like '" + result[0] + "' and f_table_name like '" +result[1] + "'"
    cursor2.execute(sql)
    connection.commit()


# 7. RECREATE ALL VIEWS
f = open("D:/tmp/view_create.sql")

error_sql = []

for line in f:
    #sql = line.strip()[:-1] # get rid of the ; last sign...
    sql = line.strip()

    try:
        cursor.execute(sql)
    except:
        error_sql.append(sql)
    connection.commit()

# We do this because we have views depending on other views (not good at all...)
for err in error_sql:
    cursor.execute(err)
    connection.commit()

f.close()

# 8. RECREATE VIEW GRANTS

for view in view_grants:
    grantee_grants = view_grants[view]
    sql = "GRANT " + grantee_grants[1] + " ON TABLE " + view + " TO \"" + grantee_grants[0] + "\""
    try:
        cursor.execute(sql)
        connection.commit()
    except:
        pass

cursor2.close()
cursor.close()
connection.close()
```

**Comment by sbrunner** [comment]
Can we close this issue ?

**Comment by kalbermattenm** [comment]
Yes...
