### ISSUE TITLE
upgrade 1.6.7rc4 make rule fail

### ISSUE THREAD

**Issue by ochriste** [camptocamp/c2cgeoportal#1806]
```
make: *** No rule to make target `tilegeneration/config.yaml', needed by `apache/tiles.conf'. Stop.
Traceback (most recent call last):
File ".build/venv/bin/c2ctool", line 9, in <module>
load_entry_point('c2cgeoportal==1.6.7rc4', 'console_scripts', 'c2ctool')()
File "/var/www/vhosts/geoportail-dev/private/1_6_7/epfl_authgeoportail/.build/venv/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 106, in main
c2ctool.upgrade()
File "/var/www/vhosts/geoportail-dev/private/1_6_7/epfl_authgeoportail/.build/venv/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 242, in upgrade
self.step2()
File "/var/www/vhosts/geoportail-dev/private/1_6_7/epfl_authgeoportail/.build/venv/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 396, in step2
check_call(["make", "-f", self.options.file, "build"])
File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'dev_1_6_7.mk', 'build']' returned non-zero exit status 2
```

**Comment by ochriste** [comment]
need to add comment in changelog to tell user to add :

DISABLE_BUILD_RULES += apache/tiles.conf 

in their makfile of they dont use the tilegeneration
