### ISSUE TITLE
upgrade to 1.6.7rc4 ERROR the variable 'reset_password' don't exists.

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1808]
from BS:

When I'm doing step 2 (.build/venv/bin/c2ctool upgrade svakom.mk 1.6.7rc4 --step 2
) I'm getting the following error message:
```...
DEST_DB= DEST_DBHOST= INSTANCE_ID=svakom APACHE_ENTRY_POINT=/svakom/ DEVELOPMENT=TRUE PACKAGE=mapbs .build/venv/bin/c2c-template --vars vars_mapbs.yaml --get-config .build/config.yaml pdfreport logo_filename intranet_default_user intranet_default_role file_proxy cube_connection sqlalchemy.url schema parentschema enable_admin_interface pyramid_closure node_modules_path closure_library_path default_locale_name servers layers available_locale_names cache admin_interface functionalities external_themes_url raster shortener hide_capabilities mapserverproxy tinyowsproxy print_url tiles_url checker check_collector default_max_age jsbuild package srid reset_password fulltextsearch
ERROR the variable 'reset_password' don't exists.
make: *** [.build/config.yaml] Error 1
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 9, in <module>
    load_entry_point('c2cgeoportal==1.6.7rc4', 'console_scripts', 'c2ctool')()
  File "/home/svakom/mapbs/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 106, in main
    c2ctool.upgrade()
  File "/home/svakom/mapbs/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 242, in upgrade
    self.step2()
  File "/home/svakom/mapbs/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 396, in step2
    check_call(["make", "-f", self.options.file, "build"])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'svakom.mk', 'build']' returned non-zero exit status 2
svakom@bvdgdi-svdmbap2:~/mapbs$
```

What can I do?

**Comment by rbovard** [comment]
Same as #1787?

**Comment by ochriste** [comment]
Yes, 
the vars_\<project\>.yaml need to be manually updated, using the https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/create/vars_+package+.yaml_tmpl file as reference.

**Comment by eleu** [comment]
ok thanks, worked for BS and it was the same as https://github.com/camptocamp/c2cgeoportal/issues/1787
