### ISSUE TITLE
Upgrade to 1.6.7

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1998]
During step 1 of upgrade to `1.6.7` (from `1.6.7rc6`), I get this error:

```
    Searching for six
    Reading https://pypi.python.org/simple/six/
    Best match: six 1.10.0
    Downloading https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55
    Processing six-1.10.0.tar.gz
    Writing /tmp/easy_install-ARZMwG/six-1.10.0/setup.cfg
    Running six-1.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ARZMwG/six-1.10.0/egg-dist-tmp-fmcwfy
    error: Setup script exited with error: Download error for https://pypi.python.org/packages/source/P/PasteDeploy/PasteDeploy-1.5.2.tar.gz#md5=352b7205c78c8de4987578d19431af3b: [Errno 110] Connection timed out

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0j8opw/PasteScript
CONST_Makefile:700: recipe for target '.build/requirements.timestamp' failed
make: *** [.build/requirements.timestamp] Error 1
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 9, in <module>
  File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 106, in main
  File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 240, in upgrade
  File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 379, in step1
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'instance_dev.mk', '.build/requirements.timestamp']' returned non-zero exit status 2
```

And after that I cannot re run the upgrade tool because it has gone...

```
-bash: .build/venv/bin/c2ctool: No such file or directory
```

Any idea of what I can do?

Thanks in advance.

**Comment by sbrunner** [comment]
`.build/venv/bin/pip install --index-url http://pypi.camptocamp.net/pypi
--find-links http://pypi.camptocamp.net/internal-pypi/index/c2cgeoportal
--trusted-host pypi.camptocamp.net c2cgeoportal==1.6.7`
and run again your step :-)

**Comment by rbovard** [comment]
Thanks but now I get:

```
  Could not find a version that satisfies the requirement pyramid-closure (from c2cgeoportal==1.6.7) (from versions: )
No matching distribution found for pyramid-closure (from c2cgeoportal==1.6.7)
```

**Comment by sbrunner** [comment]
and with?:
```bash
.build/venv/bin/pip install --index-url http://pypi.camptocamp.net/pypi --find-links http://pypi.camptocamp.net/internal-pypi/index/c2cgeoportal -e git+https://github.com/camptocamp/pyramid_closure#egg=pyramid_closure --trusted-host pypi.camptocamp.net c2cgeoportal==1.6.7
```

**Comment by rbovard** [comment]
Another error in step 1 now...

```
Could not find a version that satisfies the requirement js.jquery-jgrowl==1.2.5.post1 (from -r CONST_versions.txt (line 22)) (from versions: )
No matching distribution found for js.jquery-jgrowl==1.2.5.post1 (from -r CONST_versions.txt (line 22))
```

**Comment by sbrunner** [comment]
Do a cleanall, build and restart the upgrade ...
```bash
make -f <... .mk> cleanall
make -f <... .mk> build
...
```
And this time it should works :-)

**Comment by rbovard** [comment]
This time it's finally fine, no more timeouts...

Thanks @sbrunner and @yjacolin

**Comment by rbovard** [comment]
I don't know what happened, but I have a new error when building...

```
Collecting PasteScript==1.7.5 (from -r CONST_versions.txt (line 38))
  Downloading http://pypi.camptocamp.net/pypi/pastescript/PasteScript-1.7.5.tar.gz (129kB)
    100% |████████████████████████████████| 131kB 7.0MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/PasteScript.egg-info
    Searching for Paste>=1.3
    Reading https://pypi.python.org/simple/Paste/
    Best match: Paste 2.0.2
    Downloading https://pypi.python.org/packages/source/P/Paste/Paste-2.0.2.tar.gz#md5=4bfc8a7eaf858f6309d2ac0f40fc951c
    Processing Paste-2.0.2.tar.gz
    Writing /tmp/easy_install-STmDR_/Paste-2.0.2/setup.cfg
    Running Paste-2.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-STmDR_/Paste-2.0.2/egg-dist-tmp-O4Vk9W
    warning: no previously-included files matching '*' found under directory 'docs/_build/_sources'
    warning: no files found matching '*.html' under directory 'docs/_build'
    creating /tmp/pip-build-sA2fKZ/PasteScript/.eggs/Paste-2.0.2-py2.7.egg
    Extracting Paste-2.0.2-py2.7.egg to /tmp/pip-build-sA2fKZ/PasteScript/.eggs

    Installed /tmp/pip-build-sA2fKZ/PasteScript/.eggs/Paste-2.0.2-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-sA2fKZ/PasteScript/setup.py", line 145, in <module>
        'PasteDeploy',
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 177, in run
        ep.require(installer=installer)
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2396, in require
        list(map(working_set.add, items))
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 771, in add
        self._added_new(dist)
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 958, in _added_new
        callback(dist)
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3165, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2662, in activate
        fixup_namespace_packages(self.location)
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in fixup_namespace_packages
        subpath = _handle_ns(package, path_item)
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2186, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2204, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
      File "/var/www/vhosts/nyon-geoportail/private/dev/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in position_in_sys_path
        return sys_path.index(_normalize_cached(os.sep.join(parts)))
    ValueError: '/tmp/easy_install-STmDR_/Paste-2.0.2' is not in list

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sA2fKZ/PasteScript
CONST_Makefile:700: recipe for target '.build/requirements.timestamp' failed
make: *** [.build/requirements.timestamp] Error 1
```

I also tried to cleanall and rebuild, but this error is still there.

What's going on? Is there an issue somewhere?

**Comment by kalbermattenm** [comment]
I had the same error, see https://github.com/camptocamp/c2cgeoportal/issues/1944

**Comment by yjacolin** [comment]
idem, get this error on monday. You can install Paste with the following:

`.build/venv/bin/easy_install Paste==1.7.5.1`

**Comment by kalbermattenm** [comment]
Maybe you should try to set the version of `setuptools` by specifying the following in your `*.mk` file:

```
SETUPTOOL_VERSION ?= setuptools>=12,<19
```

I used another was around... I specified the version of setuptools in `setup.py`

There is something wrong between `Paste` and `setuptools > 19`

**Comment by kalbermattenm** [comment]
And maybe, this is something we should investigate and fix in c2cgeoportal...

**Comment by rbovard** [comment]
Thank you for your answers @kalbermattenm @yjacolin, it worked with:

> idem, get this error on monday. You can install Paste with the following:
> 
> `.build/venv/bin/easy_install Paste==1.7.5.1`

+1 for fixing this in c2cgeoportal, maybe you can open a new issue for that? (I'm not sure of what is currently wrong between Past, setuptools, etc.)

Thanks

**Comment by kalbermattenm** [comment]
@rbovard, done with https://github.com/camptocamp/c2cgeoportal/issues/2004

Maybe you should close this one....

**Comment by rbovard** [comment]
Thanks @kalbermattenm!
