### ISSUE TITLE
ImportError in nosetests

### ISSUE THREAD

**Issue by fredj** [camptocamp/c2cgeoportal#2159]
```
$ virtualenv --no-site-packages venv
$ source venv/bin/activate
$ pip install -r dev_requirements.txt
$ nosetests
Trying `CDLL(libgeos_c.so.1)`
Library path: 'libgeos_c.so.1'
DLL: <CDLL 'libgeos_c.so.1', handle 25da140 at 7f362567ae90>
Trying `CDLL(libc.so.6)`
Library path: 'libc.so.6'
DLL: <CDLL 'libc.so.6', handle 7f362a4cc9b0 at 7f362567aed0>
................E..E..........................................................
======================================================================
ERROR: test___query (papyrus.tests.test_protocol.Test_protocol)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fredj/code/papyrus/papyrus/tests/test_protocol.py", line 438, in test___query
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: test_count (papyrus.tests.test_protocol.Test_protocol)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fredj/code/papyrus/papyrus/tests/test_protocol.py", line 503, in test_count
    from mock import patch
ImportError: No module named mock

Name                                  Stmts   Miss  Cover   Missing
-------------------------------------------------------------------
papyrus.py                               29      0   100%   
papyrus/geo_interface.py                 59      0   100%   
papyrus/geojsonencoder.py                14      1    93%   21
papyrus/protocol.py                     183     39    79%   164-173, 251-257, 262-279, 283-288
papyrus/renderers.py                     40      0   100%   
papyrus/tests.py                          0      0   100%   
papyrus/tests/test_geo_interface.py     187      0   100%   
papyrus/tests/test_init.py               83      0   100%   
papyrus/tests/test_protocol.py          592     53    91%   42, 440-496, 505-516
papyrus/tests/test_renderers.py         273      0   100%   
papyrus/xsd.py                          101      5    95%   78-82
-------------------------------------------------------------------
TOTAL                                  1561     98    94%   
----------------------------------------------------------------------
Ran 78 tests in 0.485s

FAILED (errors=2)
```
Installing `mock` (`pip install mock`) fixes the issue

**Comment by fredj** [comment]
wrong repository ...
