### ISSUE TITLE
[workaround] [GMF 1.6.x] KeyError: 'url' due to c2c.template

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2181]
the following error is thrown when accessing the application: 500 Internal Server Error

In the error.log:

```
[Thu Apr 28 17:21:27.410926 2016] [wsgi:error] [pid 5395] [remote ...] mod_wsgi (pid=5395): Target WSGI script '/home/<user>/<project>/apache/application.wsgi' cannot be loaded as Python module.
[Thu Apr 28 17:21:27.411000 2016] [wsgi:error] [pid 5395] [remote ...] mod_wsgi (pid=5395): Exception occurred processing WSGI script '/home/<user>/<project>/apache/application.wsgi'.
[Thu Apr 28 17:21:27.411043 2016] [wsgi:error] [pid 5395] [remote ...] Traceback (most recent call last):
[Thu Apr 28 17:21:27.411082 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/apache/application.wsgi", line 9, in <module>
[Thu Apr 28 17:21:27.411128 2016] [wsgi:error] [pid 5395] [remote ...]     application = get_app(configfile, 'main')
[Thu Apr 28 17:21:27.411153 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/pyramid/paster.py", line 31, in get_app
[Thu Apr 28 17:21:27.411189 2016] [wsgi:error] [pid 5395] [remote ...]     global_conf=options)
[Thu Apr 28 17:21:27.411212 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Thu Apr 28 17:21:27.411247 2016] [wsgi:error] [pid 5395] [remote ...]     return loadobj(APP, uri, name=name, **kw)
[Thu Apr 28 17:21:27.411270 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Thu Apr 28 17:21:27.411303 2016] [wsgi:error] [pid 5395] [remote ...]     return context.create()
[Thu Apr 28 17:21:27.411325 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Thu Apr 28 17:21:27.411358 2016] [wsgi:error] [pid 5395] [remote ...]     return self.object_type.invoke(self)
[Thu Apr 28 17:21:27.411380 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 203, in invoke
[Thu Apr 28 17:21:27.411412 2016] [wsgi:error] [pid 5395] [remote ...]     app = context.app_context.create()
[Thu Apr 28 17:21:27.411434 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Thu Apr 28 17:21:27.411466 2016] [wsgi:error] [pid 5395] [remote ...]     return self.object_type.invoke(self)
[Thu Apr 28 17:21:27.411487 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Thu Apr 28 17:21:27.411519 2016] [wsgi:error] [pid 5395] [remote ...]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Thu Apr 28 17:21:27.411541 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
[Thu Apr 28 17:21:27.411574 2016] [wsgi:error] [pid 5395] [remote ...]     val = callable(*args, **kw)
[Thu Apr 28 17:21:27.411596 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/rudaz/__init__.py", line 19, in main
[Thu Apr 28 17:21:27.411686 2016] [wsgi:error] [pid 5395] [remote ...]     config.include("c2cgeoportal")
[Thu Apr 28 17:21:27.411714 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 788, in include
[Thu Apr 28 17:21:27.411749 2016] [wsgi:error] [pid 5395] [remote ...]     c(configurator)
[Thu Apr 28 17:21:27.411771 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/c2cgeoportal/__init__.py", line 426, in includeme
[Thu Apr 28 17:21:27.411804 2016] [wsgi:error] [pid 5395] [remote ...]     "sqlalchemy.")
[Thu Apr 28 17:21:27.411826 2016] [wsgi:error] [pid 5395] [remote ...]   File "/home/<user>/<project>/.build/venv/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 383, in engine_from_config
[Thu Apr 28 17:21:27.411860 2016] [wsgi:error] [pid 5395] [remote ...]     url = options.pop('url')
[Thu Apr 28 17:21:27.411897 2016] [wsgi:error] [pid 5395] [remote ...] KeyError: 'url'
```

**Comment by eleu** [comment]
Workaround solution:

Fix the version of c2c.template to 1.2.0

**Comment by kalbermattenm** [comment]
We just bumped into that issue... @eleu, why did you close it ?

**Comment by sbrunner** [comment]
Because it's already fixed on the branches: 
https://github.com/camptocamp/c2cgeoportal/blob/1.6/c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt
https://github.com/camptocamp/c2cgeoportal/blob/2.0/c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt

**Comment by kalbermattenm** [comment]
OK... got it... Sorry... ;-)
