### ISSUE TITLE
Updating to 2.0.0rc2

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2188]
I just ran the update (`make -f michael.mk upgrade`) and the first command:

```
make -f michael.mk upgrade1
```

I got an error...

It seems we need some kind of "new" `srid` variable in some kind of new "mapserver" template (what for...??)

What should I do to get rid of that error ?

Any hint welcomed...??

```

 Recursing into mapserver
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\pcreate.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scripts\pcreate.py", line 18, in main
    return command.run()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scripts\pcreate.py", line 88, in run
    return self.render_scaffolds()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scripts\pcreate.py", line 135, in render
_scaffolds
    scaffold.run(self, output_dir, props)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scaffolds\template.py", line 65, in run
    self.write_files(command, output_dir, vars)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scaffolds\template.py", line 97, in writ
e_files
    template_renderer=self.render_template,
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scaffolds\copydir.py", line 103, in copy
_dir
    template_renderer=template_renderer, out_=out_)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scaffolds\copydir.py", line 115, in copy
_dir
    template_renderer=template_renderer
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scaffolds\copydir.py", line 260, in subs
titute_content
    return template_renderer(content, v, filename=filename)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scaffolds\template.py", line 39, in rend
er_template
    substitute_double_braces(content, TypeMapper(vars))), fsenc)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scaffolds\template.py", line 151, in sub
stitute_double_braces
    return double_brace_pattern.sub(double_bracerepl, content)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scaffolds\template.py", line 150, in dou
ble_bracerepl
    return values[value]
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\scaffolds\template.py", line 132, in __g
etitem__
    value = eval(options[-1], dict(self.items()))
  File "<string>", line 1, in <module>
NameError: name 'srid' is not defined  in file c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeopor
tal\scaffolds\update\mapserver\CONST_example_map_mako_tmpl
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\c2ctool.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 92, in ma
in
    c2ctool.upgrade()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 210, in u
pgrade
    self.step1()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 321, in s
tep1
    "--scaffold=c2cgeoportal_update", "../%s" % self.project["project_folder"]
  File "C:\Python27\Lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.build/venv/Scripts/pcreate', '--ignore-conflicting-name', '--overwrite', '--s
caffold=c2cgeoportal_update', '../sitn_c2cgeoportal']' returned non-zero exit status 1
CONST_Makefile:1042: recipe for target 'upgrade1' failed
make: *** [upgrade1] Error 1
```

**Comment by kalbermattenm** [comment]
OK... Isn't the problem related to the fact that these <a href="https://github.com/camptocamp/c2cgeoportal/blob/2.0/doc/integrator/upgrade_application.rst.mako#L20-L24">lines</a> are not in the 2.0 doc  https://camptocamp.github.io/c2cgeoportal/2.0/integrator/upgrade_application.html ?

**Comment by kalbermattenm** [comment]
OK... This was the problem... There is nothing about that in the docs (of version 2.0.0)...

**Comment by kalbermattenm** [comment]
Next problem...
I ran `make -f michael.mk upgrade1`

And now I get...:

```
touch .build/dev-requirements.timestamp
mkdir -p .build/
npm install || sleep 20 || npm install || sleep 90 || npm install
npm WARN sitn@2.0.0 No repository field.
npm WARN sitn@2.0.0 No license field.
touch .build/node_modules.timestamp
WMTSCAPABILITIES_PATH=1.0.0/WMTSCapabilities-michael.xml INSTANCE_ID=michael APACHE_ENTRY_POINT=/michael/ DOCKER_BASE=no
 DEVELOPMENT=TRUE PACKAGE=sitn .build/venv/Scripts/c2c-template --vars vars_sitn_localdev.yaml --engine mako --files pro
ject.yaml.mako
WMTSCAPABILITIES_PATH=1.0.0/WMTSCapabilities-michael.xml INSTANCE_ID=michael APACHE_ENTRY_POINT=/michael/ DOCKER_BASE=no
 DEVELOPMENT=TRUE PACKAGE=sitn .build/venv/Scripts/c2c-template --vars vars_sitn_localdev.yaml --engine mako --files ale
mbic.ini.mako
WMTSCAPABILITIES_PATH=1.0.0/WMTSCapabilities-michael.xml INSTANCE_ID=michael APACHE_ENTRY_POINT=/michael/ DOCKER_BASE=no
 DEVELOPMENT=TRUE PACKAGE=sitn .build/venv/Scripts/c2c-template --vars vars_sitn_localdev.yaml --engine mako --files ale
mbic_static.ini.mako
.build/venv/Scripts/c2ctool upgrade michael.mk --windows  --step 2
usage: C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\c2ctool upgrade
       [--no-cleanall] [--windows] [--git-remote GITREMOTE]
       [--index-url INDEX_URL] [--c2cgeoportal-url C2CGEOPORTAL_URL]
       MAKEFILE VERSION
C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\c2ctool upgrade: error: too few arguments
CONST_Makefile:1177: recipe for target 'upgrade2' failed
make: *** [upgrade2] Error 2
```

**Comment by kalbermattenm** [comment]
Sorry... Wrong command, it was: `make -f michael.mk upgrade2` (updated my comment)

**Comment by sbrunner** [comment]
You don't miss to set the version (again)?

**Comment by kalbermattenm** [comment]
Ah......... damn myself............................

Sorry....

Now I have again the transifex issue, because Windwos does not like the SSL transifex stuff...:

If in `.tx\config`
```
[main]
host = https://www.transifex.com
...
```
Then:
```
touch --no-create sitn/locale/fr/LC_MESSAGES/sitn-client.po
msgmerge --sort-by-file --backup=none --update sitn/locale/fr/LC_MESSAGES/sitn-client.po sitn/locale/sitn-client.pot
....................... done.
echo "[https://www.transifex.com]" > "".transifexrc
echo "hostname = https://www.transifex.com" >> "".transifexrc
echo "username = c2c" >> "".transifexrc
echo "password = c2cc2c" >> "".transifexrc
echo "token =" >> "".transifexrc
/bin/sh: .build/venv/bin/python: No such file or directory
PYTHONIOENCODING=UTF-8 .build/venv/Scripts/mako-render \
        --var "tx_version=" .tx/CONST_config_mako > .tx/config
touch --no-create node_modules/ngeo/buildtools/compile-catalog.js
.build/venv/Scripts/tx pull -l fr --force
Invalid SSL certificate
CONST_Makefile:691: recipe for target '.build/locale/fr/LC_MESSAGES/gmf.po' failed
make[1]: *** [.build/locale/fr/LC_MESSAGES/gmf.po] Error 1
make[1]: Leaving directory '/cygdrive/c/git_projects/sitn_c2cgeoportal'
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\c2ctool.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 92, in ma
in
    c2ctool.upgrade()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 212, in u
pgrade
    self.step2()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 358, in s
tep2
    check_call(["make", "-f", self.options.file, "build"])
  File "C:\Python27\Lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'michael.mk', 'build']' returned non-zero exit status 2
CONST_Makefile:1177: recipe for target 'upgrade2' failed
make: *** [upgrade2] Error 1
```
Else if

```
[main]
host = http://www.transifex.com.
...
```
Then
```
touch --no-create sitn/locale/fr/LC_MESSAGES/sitn-client.po
msgmerge --sort-by-file --backup=none --update sitn/locale/fr/LC_MESSAGES/sitn-client.po sitn/locale/sitn-client.pot
....................... done.
echo "[https://www.transifex.com]" > "".transifexrc
echo "hostname = https://www.transifex.com" >> "".transifexrc
echo "username = c2c" >> "".transifexrc
echo "password = c2cc2c" >> "".transifexrc
echo "token =" >> "".transifexrc
/bin/sh: .build/venv/bin/python: No such file or directory
PYTHONIOENCODING=UTF-8 .build/venv/Scripts/mako-render \
        --var "tx_version=" .tx/CONST_config_mako > .tx/config
touch --no-create node_modules/ngeo/buildtools/compile-catalog.js
.build/venv/Scripts/tx pull -l fr --force
Exception: No user credentials found for host http://www.transifex.com. Edit ~/.transifexrc and add the appropriate info
 in there.
CONST_Makefile:691: recipe for target '.build/locale/fr/LC_MESSAGES/gmf.po' failed
make[1]: *** [.build/locale/fr/LC_MESSAGES/gmf.po] Error 1
make[1]: Leaving directory '/cygdrive/c/git_projects/sitn_c2cgeoportal'
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\c2ctool.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 92, in ma
in
    c2ctool.upgrade()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 212, in u
pgrade
    self.step2()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 358, in s
tep2
    check_call(["make", "-f", self.options.file, "build"])
  File "C:\Python27\Lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'michael.mk', 'build']' returned non-zero exit status 2
CONST_Makefile:1177: recipe for target 'upgrade2' failed
make: *** [upgrade2] Error 1

```

I cannot remember what we used as trick to surround this problem... ???

**Comment by sbrunner** [comment]
You should also edit your .transifexrc file to replace the https by http...

**Comment by kalbermattenm** [comment]
Hmmm.... you are right.... but this is actually hard coded in CONST_Makefile...:
https://github.com/camptocamp/c2cgeoportal/blob/2.0/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L678-L682

We should probably find a way to better configure.... Moreover, when I run transifex without https, I always have to say "no" to the asked question: 

```
Hostname http://www.transifex.com should be changed to https://www.transifex.com.
Change it now? [Y/n]n
```

**Comment by kalbermattenm** [comment]
Next problem...:

```
touch --no-create sitn/locale/fr/LC_MESSAGES/sitn-server.mo
.build/venv/Scripts/c2c-versions CONST_packages.yaml common main deploy ngeo
Usage: {cmd} <config file> <section>
python doesn't seam to be installed (required version: 2.7).
'dpkg' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
python-dev doesn't seam to be installed (required version: 2.7).
CONST_Makefile:985: recipe for target '.build/test-packages.timestamp' failed
make[1]: *** [.build/test-packages.timestamp] Error 1
make[1]: Leaving directory '/cygdrive/c/git_projects/sitn_c2cgeoportal'
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\c2ctool.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 92, in ma
in
    c2ctool.upgrade()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 212, in u
pgrade
    self.step2()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\scripts\c2ctool.py", line 358, in s
tep2
    check_call(["make", "-f", self.options.file, "build"])
  File "C:\Python27\Lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'michael.mk', 'build']' returned non-zero exit status 2
CONST_Makefile:1177: recipe for target 'upgrade2' failed
make: *** [upgrade2] Error 1

C:\git_projects\sitn_c2cgeoportal>.build/venv/Scripts/c2c-versions CONST_packages.yaml common main deploy ngeo
'.build' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
```

This one is new for me... ?

**Comment by ochriste** [comment]
did you disable the package version check with TEST_PACKAGES=FALSE ?

**Comment by kalbermattenm** [comment]
Yes: https://github.com/kalbermattenm/sitn_c2cgeoportal/blob/v2/sitn.mk#L47

**Comment by ochriste** [comment]
try to do the make command manually and see what error it gives you: make -f michael.mk build

**Comment by ochriste** [comment]
the '.build' is weird though, there shouldnt be a dot there

**Comment by kalbermattenm** [comment]
You are right ! In Windows this command won't work ! You always have to use backslashes... Nice catch ;-)

**Comment by kalbermattenm** [comment]
Oh no... that's not the problem...
I tried to run: `.build/venv/Scripts/c2c-versions CONST_packages.yaml common main deploy ngeo`

This actually triggers this error:
Usage: {cmd} <config file> <section>
python doesn't seam to be installed (required version: 2.7).
'dpkg' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
python-dev doesn't seam to be installed (required version: 2.7).

**Comment by ochriste** [comment]
yes, c2c-versions shouldnt be called if TEST_PACKAGES is FALSE. I dont know why it is trying to do so

**Comment by sbrunner** [comment]
I suspect that this test is wrong:
https://github.com/camptocamp/c2cgeoportal/blob/2.0/c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl#L94
can you test with
`ifndef TEST_PACKAGES`
?

**Comment by kalbermattenm** [comment]
That did the trick ! Thanks !

But... next problem:

```
.build/venv/Scripts/pot-create --config lingua-client.cfg --output sitn/locale/sitn-client.pot sitn/templates/admin_add_
user.html sitn/templates/airpages/ipc.html sitn/templates/airpages/meteodataquery.html sitn/templates/api/apidocs/map.ht
ml sitn/templates/api/apidocs/searchbox.html sitn/templates/api/apidocs/xmap.html sitn/templates/api/apihelp.html sitn/t
emplates/api/indexAPI.html sitn/templates/api/sapi/apiexamples.html sitn/templates/api/sapi/sapitutorial.html sitn/templ
ates/api/SITNlicensing.html sitn/templates/api/xapi/xapiexamples.html sitn/templates/api/xapi/xapitutorial.html sitn/tem
plates/api/xapihelp.html sitn/templates/data_templates/cadsout_disclaimer.html sitn/templates/data_templates/cadsout_met
adata.html sitn/templates/data_templates/cadsout_photo.html sitn/templates/data_templates/controlling_geoshop.html sitn/
templates/data_templates/controlling_syncserver.html sitn/templates/data_templates/di01_hydrants_intranet.html sitn/temp
lates/data_templates/di06_sites_opam.html sitn/templates/data_templates/di07_opam_prod_chimiques.html sitn/templates/dat
a_templates/di09_opam_responsable.html sitn/templates/data_templates/di10_opam_genre_activite.html sitn/templates/data_t
emplates/di11_opam_prod_stock.html sitn/templates/data_templates/dn_reports.html sitn/templates/data_templates/ecomorpho
logie.html sitn/templates/data_templates/eg10_panneaux_bati_pv.html sitn/templates/data_templates/eg11_panneaux_face_pv.
html sitn/templates/data_templates/eg13_panneaux_face_toit_thermique.html sitn/templates/data_templates/en12_citbru_auto
risations.html sitn/templates/data_templates/en13_citbru_locaux_citernes.html sitn/templates/data_templates/en14_citbru_
locaux_chauffage.html sitn/templates/data_templates/en19_citbru_reservoirs.html sitn/templates/data_templates/en20_citbr
u_citernes.html sitn/templates/data_templates/en21_citbru_chauffages.html sitn/templates/data_templates/en_citbru_rappor
ts.html sitn/templates/data_templates/en_citbru_repondant.html sitn/templates/data_templates/fo10_unite_gestion_pgi.html
 sitn/templates/data_templates/geone_details_affaire.html sitn/templates/data_templates/geone_parcelles_deposees.html si
tn/templates/data_templates/geone_parcelles_rf.html sitn/templates/data_templates/hy06_points_injection.html sitn/templa
tes/data_templates/hy12_reapparition.html sitn/templates/data_templates/infolica_check_terris.html sitn/templates/data_t
emplates/metadata.html sitn/templates/data_templates/metadata_show.html sitn/templates/data_templates/orthophoto_lubis.h
tml sitn/templates/data_templates/pa01_recensement_archi.html sitn/templates/data_templates/pa02_patrimoine_archi.html s
itn/templates/data_templates/patri_immo_etat_detail.html sitn/templates/data_templates/po01_cicop.html sitn/templates/da
ta_templates/prop_etat_suivi_print.html sitn/templates/data_templates/sante_defi_add.html sitn/templates/data_templates/
sat_suivi_print.html sitn/templates/data_templates/st01_defibillateur.html sitn/templates/data_templates/st03_contact_ur
gence.html sitn/templates/data_templates/tc04_ruchers_list.html sitn/templates/data_templates/traffic_event_show.html si
tn/templates/data_templates/users_layer_list.html sitn/templates/data_templates/vt10_parcelles_viticoles.html sitn/templ
ates/data_templates/vt8_sols.html sitn/templates/data_templates/waterquality_ex11.html sitn/templates/data_templates/wat
erquality_qlt_city_ne.html sitn/templates/data_templates/waterquality_qlt_lakes.html sitn/templates/data_templates/water
quality_qlt_subsurf.html sitn/templates/data_templates/waterquality_qlt_surf.html sitn/templates/edit.html sitn/template
s/help_templates/help.html sitn/templates/help_templates/help_contact.html sitn/templates/help_templates/help_extract.ht
ml sitn/templates/help_templates/help_faq.html sitn/templates/help_templates/help_header.html sitn/templates/help_templa
tes/help_webservices.html sitn/templates/index.html sitn/templates/mobile.html sitn/templates/owner.html sitn/templates/
routing.html sitn/templates/search-tip.html sitn/static-ngeo/js/mobile.js sitn/static-ngeo/js/sitnmodule.js  .build/conf
ig.yaml development.ini
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\pot-create.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\lingua\extract.py", line 280, in main
    for message in extractor(real_filename, options):
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\lingua_extractor.py", line 97,
in __call__
    self.env = bootstrap(filename)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\paster.py", line 131, in bootstrap
    app = get_app(config_uri, options=options)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\paster.py", line 31, in get_app
    global_conf=options)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\paste\deploy\loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\paste\deploy\loadwsgi.py", line 272, in loadobj
    return context.create()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\paste\deploy\loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\paste\deploy\loadwsgi.py", line 203, in invoke
    app = context.app_context.create()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\paste\deploy\loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\paste\deploy\loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\paste\deploy\util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "c:\git_projects\sitn_c2cgeoportal\sitn\__init__.py", line 335, in main
    config.scan()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pyramid\config\__init__.py", line 974, in scan
    ignore=ignore)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\venusian\__init__.py", line 205, in scan
    __import__(modname)
  File "c:\git_projects\sitn_c2cgeoportal\sitn\version.py", line 4
    "git_hash": "4e7d8354518bdec41b6376ae87fba65e7627b1b5",
             ^
SyntaxError: invalid syntax
CONST_Makefile:642: recipe for target 'sitn/locale/sitn-client.pot' failed
make: *** [sitn/locale/sitn-client.pot] Error 1
```

And I do not know where to search (or in which template....)

**Comment by sbrunner** [comment]
can you also add the content if the `c:\git_projects\sitn_c2cgeoportal\sitn\version.py` file?

**Comment by kalbermattenm** [comment]
```python
# Auto-generated file. Do not Edit!
INFO = {
paf
    "git_hash": "4e7d8354518bdec41b6376ae87fba65e7627b1b5",
    "version": "1.0",
    "git_tag": "None",
}
```

my FAULT.... don't ask... `paf` has nothing to do here... I corrected it, sorry (getting tired...)

For your information, I was now able to run `make -f michael.mk upgrade2` without errors (and with quite a lot of help coming from your side....)

I will continue tomorrow with the next step.

**Comment by ochriste** [comment]
about the transifex problem, it should be fixed by https://github.com/camptocamp/c2cgeoportal/blob/2.0/c2cgeoportal/scaffolds/update/CONST_dev-requirements.txt#L7

verify you have the right line in your CONST_dev-requirements.txt
also delete the exiting transifex-client folder in your .build\venv\Lib\site-packages and try to run the make again to reinstall this package

**Comment by kalbermattenm** [comment]
Thanks @ochriste ! Effectively, I uninstalled transifex-client (using pip uninstall) and re-running make does not pop up anymore the yes/no question about using https instead of http...

**Comment by sbrunner** [comment]
I think that this issue can be closed, if not reopen it :-)
