### ISSUE TITLE
Upgrade to 1.6.8rc2 Step 1: NameError: name 'srid' is not defined

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2229]
I tried to upgrade to Version 1.6.8rc2 from 1.6.7 but I got the following error while Step 1:
Any ideas?

```
Traceback (most recent call last):
  File ".build/venv/bin/pcreate", line 9, in <module>
    load_entry_point('pyramid==1.6.dev0', 'console_scripts', 'pcreate')()
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scripts/pcreate.py", line 16, in main
    return command.run()
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scripts/pcreate.py", line 85, in run
    return self.render_scaffolds()
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scripts/pcreate.py", line 124, in render_scaffolds
    scaffold.run(self, output_dir, vars)
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/template.py", line 65, in run
    self.write_files(command, output_dir, vars)
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/template.py", line 97, in write_files
    template_renderer=self.render_template,
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/copydir.py", line 103, in copy_dir
    template_renderer=template_renderer, out_=out_)
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/copydir.py", line 115, in copy_dir
    template_renderer=template_renderer
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/copydir.py", line 260, in substitute_content
    return template_renderer(content, v, filename=filename)
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/template.py", line 39, in render_template
    substitute_double_braces(content, TypeMapper(vars))), fsenc)
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/template.py", line 151, in substitute_double_braces
    return double_brace_pattern.sub(double_bracerepl, content)
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/template.py", line 150, in double_bracerepl
    return values[value]
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/template.py", line 132, in __getitem__
    value = eval(options[-1], dict(self.items()))
  File "<string>", line 1, in <module>
NameError: name 'srid' is not defined  in file /home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scaffolds/update/mapserver/CONST_example_map_mako_tmpl
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 9, in <module>
    load_entry_point('c2cgeoportal==1.6.8rc2', 'console_scripts', 'c2ctool')()
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 106, in main
    c2ctool.upgrade()
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 240, in upgrade
    elif self.options.step == 1:
  File "/home/svadip/mapbs/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 363, in step1
    "%s/pcreate" % self.venv_bin, "--overwrite", "--scaffold=c2cgeoportal_update",
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.build/venv/bin/pcreate', '--overwrite', '--scaffold=c2cgeoportal_update', '../mapbs', 'package=mapbs']' returned non-zero exit status 1
```

**Comment by ochriste** [comment]
verify that the project.yaml.mako file has the correct content,
see 
https://github.com/camptocamp/c2cgeoportal/commit/34bb0b2a72fbe32f1e8e85899ab169ce7a6b2c96

**Comment by sbrunner** [comment]
See the doc: http://docs.camptocamp.net/c2cgeoportal/1.6/integrator/upgrade_application.html#easy-upgrading-an-application
