### ISSUE TITLE
edit interface broken in 2.1

### ISSUE THREAD

**Issue by fredj** [camptocamp/c2cgeoportal#2252]
https://geomapfish-demo.camptocamp.net/2.1/edit

apache error.log:
```
[Thu May 19 15:55:58.437863 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543] Traceback (most recent call last):
[Thu May 19 15:55:58.437886 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]   File "/var/www/vhosts/geomapfish-demo/private/2.1/.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
[Thu May 19 15:55:58.437911 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]     result = template.render_unicode(**system)
[Thu May 19 15:55:58.437933 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]   File "/var/www/vhosts/geomapfish-demo/private/2.1/.build/venv/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
[Thu May 19 15:55:58.437973 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]     as_unicode=True)
[Thu May 19 15:55:58.437997 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]   File "/var/www/vhosts/geomapfish-demo/private/2.1/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
[Thu May 19 15:55:58.438020 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]     **_kwargs_for_callable(callable_, data))
[Thu May 19 15:55:58.438042 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]   File "/var/www/vhosts/geomapfish-demo/private/2.1/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
[Thu May 19 15:55:58.438065 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
[Thu May 19 15:55:58.438088 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]   File "/var/www/vhosts/geomapfish-demo/private/2.1/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
[Thu May 19 15:55:58.438111 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]     callable_(context, *args, **kwargs)
[Thu May 19 15:55:58.438134 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]   File "/var/www/vhosts/geomapfish-demo/private/2.1/demo/templates/edit.js", line 12, in render_body
[Thu May 19 15:55:58.438157 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]     OpenLayers.ProxyHost = "${request.route_url('ogcproxy') | n}?url=";
[Thu May 19 15:55:58.438180 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]   File "/var/www/vhosts/geomapfish-demo/private/2.1/.build/venv/lib/python2.7/site-packages/pyramid/url.py", line 266, in route_url
[Thu May 19 15:55:58.438202 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543]     raise KeyError('No such route named %s' % route_name)
[Thu May 19 15:55:58.438224 2016] [wsgi:error] [pid 26220] [remote 128.179.66.4:21543] KeyError: 'No such route named ogcproxy'


```

**Comment by sbrunner** [comment]
Fixed with https://github.com/camptocamp/demo_geomapfish/commit/7e8fb9e41c6306073f50eba358117740430f916d
