### ISSUE TITLE
Error when upgrading to 2.0.0rc6

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2342]
I get the following error when running make -f v2.mk upgrade1 
```
chmod: changing permissions of â/tmp/cartoriviera_geomapfish/deploy/hooks/post-restore-codeâ: Operation not permitted
Traceback (most recent call last):
  File ".build/venv/bin/pcreate", line 11, in <module>
    sys.exit(main())
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/pyramid/scripts/pcreate.py", line 18, in main
    return command.run()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/pyramid/scripts/pcreate.py", line 88, in run
    return self.render_scaffolds()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/pyramid/scripts/pcreate.py", line 135, in render_scaffolds
    scaffold.run(self, output_dir, props)
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/pyramid/scaffolds/template.py", line 66, in run
    self.post(command, output_dir, vars)
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scaffolds/__init__.py", line 160, in post
    subprocess.check_call(["chmod", "+x", dest])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['chmod', '+x', '/tmp/cartoriviera_geomapfish/deploy/hooks/post-restore-code']' returned non-zero exit status 1
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 99, in main
    c2ctool.upgrade()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 217, in upgrade
    self.step1()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 369, in step1
    check_call(pcreate_cmd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.build/venv/bin/pcreate', '--ignore-conflicting-name', '--scaffold=c2cgeoportal_create', '/tmp/cartoriviera_geomapfish', 'srid=21781', 'mobile_application_title=Cartoriviera mobile', 'apache_vhost=cartoriviera_preprod', 'extent=540000, 127000, 580000, 157000', 'package=cartoriviera']' returned non-zero exit status 1
CONST_Makefile:1182: recipe for target 'upgrade1' failed
make: *** [upgrade1] Error 1
```

**Comment by sbrunner** [comment]
It's my fault, I just delete the folder, you can rerun the `upgrade1` :-)

**Comment by gnerred** [comment]
Thanks, the upgrade1 is now OK
