### ISSUE TITLE
AssertionError: desktop.js not in [...]

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2565]
During step 4 of upgrade I have this issue:

```
.build/venv/bin/c2c-template --vars vars_nyon.yaml --engine mako --files jsbuild/app.cfg.mako
mkdir -p nyon/static/build/
.build/venv/bin/jsbuild jsbuild/app.cfg --uncompress -j desktop.js -o nyon/static/build
Traceback (most recent call last):
  File ".build/venv/bin/jsbuild", line 11, in <module>
    load_entry_point('JSTools==0.6', 'console_scripts', 'jsbuild')()
  File ".build/venv/local/lib/python2.7/site-packages/jstools/build.py", line 96, in build
    command()
  File ".build/venv/local/lib/python2.7/site-packages/jstools/utils.py", line 31, in caller
    return func(args, options, optparser)
  File ".build/venv/local/lib/python2.7/site-packages/jstools/build.py", line 87, in default_merge
    list_only=options.list_only)
  File ".build/venv/local/lib/python2.7/site-packages/jstools/merge.py", line 304, in run
    assert single in sections, ValueError("%s not in %s" %(single, sections))
AssertionError: desktop.js not in ['app.js', 'edit.js', 'lang-en.js', 'lang-fr.js', 'lang-de.js', 'api.js', 'api-lang-en.js', 'api-lang-fr.js', 'api-lang-de.js', 'xapi.js', 'routing.js']
CONST_Makefile:996: recipe for target 'nyon/static/build/desktop.js' failed
make[1]: *** [nyon/static/build/desktop.js] Error 1
make[1]: Leaving directory 'v2'
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 98, in main
    c2ctool.upgrade()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 222, in upgrade
    self.step4()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 436, in step4
    check_call(["make", "-f", self.options.file, "build"])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'instance_v2.mk', 'build']' returned non-zero exit status 2
CONST_Makefile:1237: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error 1
```

I followed the instructions to keep cgxp but maybe something went wrong?

**Comment by sbrunner** [comment]
The missing point is that you should rename the `app.js` section into `desktop.js` in the jsbuild/app.cfg.mako` :-)

**Comment by rbovard** [comment]
Thanks!
