### ISSUE TITLE
Could not create unique index during the upgrade

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#2568]
If you have this kind of error:

```
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) could not create unique index "type_name_unique_treeitem"
DETAIL:  Key (type, name)=(layerv1, orthos_2013) is duplicated.
 [SQL: 'ALTER TABLE main.treeitem ADD CONSTRAINT type_name_unique_treeitem UNIQUE (type, name)']
CONST_Makefile:1237: recipe for target 'upgrade4' failed
```

It mean that you have two tree item of the same type with the same neme, and it's not allowed anymore,
in this case we have two layerv1 with the name ortho_2013.

Full stach:

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade daf738d5bae4 -> b60f2a505f42, Remame UIMetadata to Metadata
INFO  [alembic.runtime.migration] Running upgrade b60f2a505f42 -> 8117bb9bba16, Use dimension on all the layers
INFO  [alembic.runtime.migration] Running upgrade 8117bb9bba16 -> e7e03dedade3, Put the default WMS server in the servers part, add some constrains
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 98, in main
    c2ctool.upgrade()
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 222, in upgrade
    self.step4()
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 438, in step4
    command.upgrade(Config("alembic.ini"), "head")
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "CONST_alembic/main/env.py", line 109, in <module>
    run_migrations_online()
  File "CONST_alembic/main/env.py", line 102, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/project_path/CONST_alembic/main/versions/e7e03dedade3_put_the_default_wms_server_in_the_.py", line 59, in upgrade
    'type_name_unique_treeitem', 'treeitem', ['type', 'name'], schema=schema
  File "<string>", line 8, in create_unique_constraint
  File "<string>", line 3, in create_unique_constraint
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/operations/ops.py", line 394, in create_unique_constraint
    return operations.invoke(op)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 135, in create_constraint
    operation.to_constraint(operations.migration_context)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 180, in add_constraint
    self._exec(schema.AddConstraint(const))
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/project_path/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) could not create unique index "type_name_unique_treeitem"
DETAIL:  Key (type, name)=(layerv1, orthos_2013) is duplicated.
 [SQL: 'ALTER TABLE main.treeitem ADD CONSTRAINT type_name_unique_treeitem UNIQUE (type, name)']
CONST_Makefile:1237: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error 1
```

**Comment by sbrunner** [comment]
Alternative:

```
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) could not create unique index "name_unique_ogc_server"
DETAIL:  Key (name)=(source for config://my_wmtscapabilities) is duplicated.
 [SQL: 'ALTER TABLE main.ogc_server ADD CONSTRAINT name_unique_ogc_server UNIQUE (name)']
CONST_Makefile:1237: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error
```
this mean that you have tow OGC server with the same name `config://my_wmtscapabilities` and it's not allowed anymore.
