### ISSUE TITLE
Recipe for target 'apache/mapcache.xml' failed

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2575]
Next error in step 4 of upgrade script:

```
CONST_Makefile:1131: recipe for target 'apache/mapcache.xml' failed
make[1]: *** [apache/mapcache.xml] Error 1
make[1]: Leaving directory '/var/www/vhosts/nyon-geoportail/private/v2'
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 98, in main
    c2ctool.upgrade()
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 222, in upgrade
    self.step4()
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 436, in step4
    check_call(["make", "-f", self.options.file, "build"])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'instance_v2.mk', 'build']' returned non-zero exit status 2
CONST_Makefile:1237: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error 1
```

**Comment by sbrunner** [comment]
You don't have something before in the console log?

**Comment by rbovard** [comment]
Yes:

```
make -f instance_v2.mk upgrade4
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
.build/venv/bin/c2ctool upgrade instance_v2.mk  --step 4
make[1]: Entering directory 'v2'
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
msgfmt -o nyon/locale/fr/LC_MESSAGES/nyon-server.mo nyon/locale/fr/LC_MESSAGES/nyon-server.po
touch --no-create nyon/locale/fr/LC_MESSAGES/nyon-server.mo
.build/venv/bin/generate_controller --generate-mapcache-config
ERROR:tilecloud_chain:__init__:The config file 'tilegeneration/config.yaml' in invalid.
 - /: Key 'layer_default' was not defined.
 - /layers/alt_2002_courbes_niveau_1m: Cannot find required key 'extension'.
 - /layers/alt_2002_courbes_niveau_1m: Cannot find required key 'grid'.
 - /layers/alt_2002_courbes_niveau_1m: Cannot find required key 'mime_type'.
 - /layers/alt_2002_courbes_niveau_1m: Cannot find required key 'wmts_style'.
 - /layers/alt_2013_courbes_niveau_1m: Cannot find required key 'extension'.
 - /layers/alt_2013_courbes_niveau_1m: Cannot find required key 'grid'.
 - /layers/alt_2013_courbes_niveau_1m: Cannot find required key 'mime_type'.
 - /layers/alt_2013_courbes_niveau_1m: Cannot find required key 'wmts_style'.
 - /layers/arch_1806_plan_de_ville: Cannot find required key 'extension'.
 - /layers/arch_1806_plan_de_ville: Cannot find required key 'grid'.
 - /layers/arch_1806_plan_de_ville: Cannot find required key 'mime_type'.
 - /layers/arch_1806_plan_de_ville: Cannot find required key 'wmts_style'.
 - /layers/arch_1940_plan_d_ensemble: Cannot find required key 'extension'.
 - /layers/arch_1940_plan_d_ensemble: Cannot find required key 'grid'.
 - /layers/arch_1940_plan_d_ensemble: Cannot find required key 'mime_type'.
 - /layers/arch_1940_plan_d_ensemble: Cannot find required key 'wmts_style'.
 - /layers/at_plans_quartier_raster: Cannot find required key 'extension'.
 - /layers/at_plans_quartier_raster: Cannot find required key 'grid'.
 - /layers/at_plans_quartier_raster: Cannot find required key 'mime_type'.
 - /layers/at_plans_quartier_raster: Cannot find required key 'wmts_style'.
 - /layers/cartes_nationales: Cannot find required key 'extension'.
 - /layers/cartes_nationales: Cannot find required key 'grid'.
 - /layers/cartes_nationales: Cannot find required key 'mime_type'.
 - /layers/cartes_nationales: Cannot find required key 'wmts_style'.
 - /layers/mns_2002_ombrage_1m: Cannot find required key 'grid'.
 - /layers/mns_2002_ombrage_1m: Cannot find required key 'wmts_style'.
 - /layers/mns_2013_ombrage_50cm: Cannot find required key 'grid'.
 - /layers/mns_2013_ombrage_50cm: Cannot find required key 'wmts_style'.
 - /layers/mnt_2002_ombrage_1m: Cannot find required key 'grid'.
 - /layers/mnt_2002_ombrage_1m: Cannot find required key 'wmts_style'.
 - /layers/mnt_2013_ombrage_50cm: Cannot find required key 'grid'.
 - /layers/mnt_2013_ombrage_50cm: Cannot find required key 'wmts_style'.
 - /layers/orthophotos_sitnyon_ete_2009_30cm: Cannot find required key 'grid'.
 - /layers/orthophotos_sitnyon_ete_2009_30cm: Cannot find required key 'wmts_style'.
 - /layers/orthophotos_sitnyon_ete_2010_5cm: Cannot find required key 'grid'.
 - /layers/orthophotos_sitnyon_ete_2010_5cm: Cannot find required key 'wmts_style'.
 - /layers/orthophotos_sitnyon_printemps_2016_5cm: Cannot find required key 'grid'.
 - /layers/orthophotos_sitnyon_printemps_2016_5cm: Cannot find required key 'wmts_style'.
 - /layers/orthophotos_swissimage_ete_2004_50cm: Cannot find required key 'grid'.
 - /layers/orthophotos_swissimage_ete_2004_50cm: Cannot find required key 'wmts_style'.
 - /layers/orthophotos_swissimage_ete_2006_25cm: Cannot find required key 'grid'.
 - /layers/orthophotos_swissimage_ete_2006_25cm: Cannot find required key 'wmts_style'.
 - /layers/orthophotos_swissimage_ete_2012_25cm: Cannot find required key 'grid'.
 - /layers/orthophotos_swissimage_ete_2012_25cm: Cannot find required key 'wmts_style'.
 - /layers/orthophotos_swissimage_hiver_2015_25cm: Cannot find required key 'grid'.
 - /layers/orthophotos_swissimage_hiver_2015_25cm: Cannot find required key 'wmts_style'.
 - /layers/orthophotos_swissphoto_ete_2002_50cm: Cannot find required key 'grid'.
 - /layers/orthophotos_swissphoto_ete_2002_50cm: Cannot find required key 'wmts_style'.
 - /layers/plan_cadastral: Cannot find required key 'extension'.
 - /layers/plan_cadastral: Cannot find required key 'grid'.
 - /layers/plan_cadastral: Cannot find required key 'mime_type'.
 - /layers/plan_cadastral: Cannot find required key 'wmts_style'.
 - /layers/rayonnement_solaire_2013: Cannot find required key 'grid'.
 - /layers/rayonnement_solaire_2013: Cannot find required key 'wmts_style'.
 - /layers/tr_plan_ouvrage_raster: Cannot find required key 'extension'.
 - /layers/tr_plan_ouvrage_raster: Cannot find required key 'grid'.
 - /layers/tr_plan_ouvrage_raster: Cannot find required key 'mime_type'.
 - /layers/tr_plan_ouvrage_raster: Cannot find required key 'wmts_style'.
CONST_Makefile:1131: recipe for target 'apache/mapcache.xml' failed
make[1]: *** [apache/mapcache.xml] Error 1
make[1]: Leaving directory 'v2'
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 98, in main
    c2ctool.upgrade()
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 222, in upgrade
    self.step4()
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 436, in step4
    check_call(["make", "-f", self.options.file, "build"])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'instance_v2.mk', 'build']' returned non-zero exit status 2
CONST_Makefile:1237: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error 1
```

**Comment by sbrunner** [comment]
Have a look on https://github.com/camptocamp/c2cgeoportal/pull/2569/files#diff-42e09bd71078cd58ef96bdf94063002cR160 :-)

**Comment by rbovard** [comment]
Ok, now I have:

```
$ make -f instance_v2.mk upgrade4
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
.build/venv/bin/c2ctool upgrade instance_v2.mk  --step 4
make[1]: Entering directory 'v2'
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
.build/venv/bin/c2c-template --vars vars_nyon.yaml --engine mako --files tilegeneration/config.yaml.mako
msgfmt -o nyon/locale/fr/LC_MESSAGES/nyon-server.mo nyon/locale/fr/LC_MESSAGES/nyon-server.po
touch --no-create nyon/locale/fr/LC_MESSAGES/nyon-server.mo
.build/venv/bin/generate_controller --generate-mapcache-config
Traceback (most recent call last):
  File ".build/venv/bin/generate_controller", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/tilecloud_chain/controller.py", line 85, in main
    _generate_mapcache_config(gene)
  File ".build/venv/local/lib/python2.7/site-packages/tilecloud_chain/controller.py", line 275, in _generate_mapcache_config
    sorted=sorted,
  File ".build/venv/bin/bottle.py", line 3609, in template
    return TEMPLATES[tplid].render(kwargs)
  File ".build/venv/bin/bottle.py", line 3322, in render
    return self.tpl.render(**_defaults)
  File ".build/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File ".build/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 55, in top-level template code
TypeError: sequence item 0: expected string, int found
CONST_Makefile:1131: recipe for target 'apache/mapcache.xml' failed
make[1]: *** [apache/mapcache.xml] Error 1
make[1]: Leaving directory 'v2'
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 98, in main
    c2ctool.upgrade()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 222, in upgrade
    self.step4()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 436, in step4
    check_call(["make", "-f", self.options.file, "build"])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'instance_v2.mk', 'build']' returned non-zero exit status 2
CONST_Makefile:1237: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error 1
```

**Comment by sbrunner** [comment]
I just update the pull request to add `And if the dimensions are a number like 2016 they should be quoted => '2016'.` :-)

**Comment by rbovard** [comment]
Ok thanks, now I have an other issue not related...
