### ISSUE TITLE
Errors when upgrading database with alembic scripts

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2578]
Still during step 4...:

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 29f2a32859ec -> 951ff84bd8ec, Be able to delete a WMS layer in SQL
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 98, in main
    c2ctool.upgrade()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 222, in upgrade
    self.step4()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 438, in step4
    command.upgrade(Config("alembic.ini"), "head")
  File ".build/venv/local/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File ".build/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File ".build/venv/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File ".build/venv/local/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "CONST_alembic/main/env.py", line 109, in <module>
    run_migrations_online()
  File "CONST_alembic/main/env.py", line 102, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File ".build/venv/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File ".build/venv/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "CONST_alembic/main/versions/951ff84bd8ec_be_able_to_delete_a_wms_layer_in_sql.py", line 80, in upgrade
    'layer_id_fkey', 'layer', schema=schema,
  File "<string>", line 8, in drop_constraint
  File "<string>", line 3, in drop_constraint
  File ".build/venv/local/lib/python2.7/site-packages/alembic/operations/ops.py", line 145, in drop_constraint
    return operations.invoke(op)
  File ".build/venv/local/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File ".build/venv/local/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 146, in drop_constraint
    schema=operation.schema,
  File ".build/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 183, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File ".build/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) constraint "layer_id_fkey" of relation "layer" does not exist
 [SQL: 'ALTER TABLE main.layer DROP CONSTRAINT layer_id_fkey']
CONST_Makefile:1237: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error 1
```

**Comment by sbrunner** [comment]
You have strange index and constaint name, than you should do to have the correct names (untsted):
```
ALTER INDEX layertmp_pkey RENAME TO layer2_pkey;
ALTER TABLE main.layer RENAME CONSTRAINT layertmp_id_fkey TO layer_id_fkey;
```

**Comment by rbovard** [comment]
There is no index for this table...

```
CREATE TABLE main.layer
(
  id integer NOT NULL,
  public boolean,
  geo_table character varying,
  exclude_properties character varying,
  CONSTRAINT layertmp_pkey PRIMARY KEY (id),
  CONSTRAINT layertmp_id_fkey FOREIGN KEY (id)
      REFERENCES main.treeitem (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
```

**Comment by rbovard** [comment]
It's better with

```
ALTER TABLE main.layer RENAME CONSTRAINT layertmp_pkey TO layer2_pkey;
ALTER TABLE main.layer RENAME CONSTRAINT layertmp_id_fkey TO layer_id_fkey;
```

But now I have:

```
$ make -f instance_v2.mk upgrade4
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
.build/venv/bin/c2ctool upgrade instance_v2.mk  --step 4
make[1]: Entering directory '/var/www/vhosts/nyon-geoportail/private/v2'
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
msgfmt -o nyon/locale/fr/LC_MESSAGES/nyon-server.mo nyon/locale/fr/LC_MESSAGES/nyon-server.po
touch --no-create nyon/locale/fr/LC_MESSAGES/nyon-server.mo
sudo /usr/sbin/apache2ctl graceful
touch .build/apache.timestamp
make[1]: Leaving directory '/var/www/vhosts/nyon-geoportail/private/v2'
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 29f2a32859ec -> 951ff84bd8ec, Be able to delete a WMS layer in SQL
INFO  [alembic.runtime.migration] Running upgrade 29f2a32859ec -> 6a412d9437b1, Rename ServerOGC to OGCServer
INFO  [alembic.runtime.migration] Running upgrade 6a412d9437b1, 951ff84bd8ec -> daf738d5bae4, Merge 2.0 and master branches
INFO  [alembic.runtime.migration] Running upgrade daf738d5bae4 -> b60f2a505f42, Remame UIMetadata to Metadata
INFO  [alembic.runtime.migration] Running upgrade b60f2a505f42 -> 8117bb9bba16, Use dimension on all the layers
INFO  [alembic.runtime.migration] Running upgrade 8117bb9bba16 -> e7e03dedade3, Put the default WMS server in the servers part, add some constrains
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 98, in main
    c2ctool.upgrade()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 222, in upgrade
    self.step4()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 438, in step4
    command.upgrade(Config("alembic.ini"), "head")
  File ".build/venv/local/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File ".build/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File ".build/venv/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File ".build/venv/local/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "CONST_alembic/main/env.py", line 109, in <module>
    run_migrations_online()
  File "CONST_alembic/main/env.py", line 102, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File ".build/venv/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File ".build/venv/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "CONST_alembic/main/versions/e7e03dedade3_put_the_default_wms_server_in_the_.py", line 56, in upgrade
    op.create_unique_constraint('name_unique_ogc_server', 'ogc_server', ['name'], schema=schema)
  File "<string>", line 8, in create_unique_constraint
  File "<string>", line 3, in create_unique_constraint
  File ".build/venv/local/lib/python2.7/site-packages/alembic/operations/ops.py", line 394, in create_unique_constraint
    return operations.invoke(op)
  File ".build/venv/local/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File ".build/venv/local/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 135, in create_constraint
    operation.to_constraint(operations.migration_context)
  File ".build/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 180, in add_constraint
    self._exec(schema.AddConstraint(const))
  File ".build/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File ".build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) could not create unique index "name_unique_ogc_server"
DETAIL:  Key (name)=(source for config://my_wmtscapabilities) is duplicated.
 [SQL: 'ALTER TABLE main.ogc_server ADD CONSTRAINT name_unique_ogc_server UNIQUE (name)']
CONST_Makefile:1237: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error 1
```

**Comment by sbrunner** [comment]
This mean that you have tow OGC server with the same name `source for config://my_wmtscapabilities`, I don't understand why you have them..., for me you can remove all OGC server that reference a WMTS capabilities...

**Comment by rbovard** [comment]
The `image_type` is different: `image/png` `image/jpeg`

**Comment by sbrunner** [comment]
Yes I see it but where do you use them?
Normally the OGC server point to WMS/WFS servers not WMTS ...

... I just see our error here https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scripts/themev1tov2.py#L120-L124 we shouldn't take the wmts layers! to be fixed

**Comment by rbovard** [comment]
So I need to rerun fixed themev1tov2 script?

**Comment by sbrunner** [comment]
no not nessesery

**Comment by sbrunner** [comment]
you can just remove the ogc servers related to wmts capabilities, do you want that i do it?

**Comment by rbovard** [comment]
Ok, done.

Now other errors...

```
$ make -f instance_v2.mk upgrade4
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
.build/venv/bin/c2ctool upgrade instance_v2.mk  --step 4
make[1]: Entering directory 'v2'
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
find: `nyon/static-ngeo/components': No such file or directory
msgfmt -o nyon/locale/fr/LC_MESSAGES/nyon-server.mo nyon/locale/fr/LC_MESSAGES/nyon-server.po
touch --no-create nyon/locale/fr/LC_MESSAGES/nyon-server.mo
sudo /usr/sbin/apache2ctl graceful
touch .build/apache.timestamp
make[1]: Leaving directory 'v2'
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 29f2a32859ec -> 951ff84bd8ec, Be able to delete a WMS layer in SQL
INFO  [alembic.runtime.migration] Running upgrade 29f2a32859ec -> 6a412d9437b1, Rename ServerOGC to OGCServer
INFO  [alembic.runtime.migration] Running upgrade 6a412d9437b1, 951ff84bd8ec -> daf738d5bae4, Merge 2.0 and master branches
INFO  [alembic.runtime.migration] Running upgrade daf738d5bae4 -> b60f2a505f42, Remame UIMetadata to Metadata
INFO  [alembic.runtime.migration] Running upgrade b60f2a505f42 -> 8117bb9bba16, Use dimension on all the layers
INFO  [alembic.runtime.migration] Running upgrade 8117bb9bba16 -> e7e03dedade3, Put the default WMS server in the servers part, add some constrains
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 98, in main
    c2ctool.upgrade()
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 222, in upgrade
    self.step4()
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 438, in step4
    command.upgrade(Config("alembic.ini"), "head")
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "CONST_alembic/main/env.py", line 109, in <module>
    run_migrations_online()
  File "CONST_alembic/main/env.py", line 102, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "v2/CONST_alembic/main/versions/e7e03dedade3_put_the_default_wms_server_in_the_.py", line 59, in upgrade
    'type_name_unique_treeitem', 'treeitem', ['type', 'name'], schema=schema
  File "<string>", line 8, in create_unique_constraint
  File "<string>", line 3, in create_unique_constraint
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/operations/ops.py", line 394, in create_unique_constraint
    return operations.invoke(op)
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 135, in create_constraint
    operation.to_constraint(operations.migration_context)
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 180, in add_constraint
    self._exec(schema.AddConstraint(const))
  File "v2/.build/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "v2/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "v2/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "v2/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File "v2/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "v2/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "v2/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "v2/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "v2/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) could not create unique index "type_name_unique_treeitem"
DETAIL:  Key (type, name)=(layerv1, ass_collecteur_ec) is duplicated.
 [SQL: 'ALTER TABLE main.treeitem ADD CONSTRAINT type_name_unique_treeitem UNIQUE (type, name)']
CONST_Makefile:1237: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error 1
```

**Comment by sbrunner** [comment]
You steel have two layerv1 named `ass_collecteur_ec`

**Comment by rbovard** [comment]
It's no more possible to have same names for layers?!

**Comment by rbovard** [comment]
... and for groups?

**Comment by rbovard** [comment]
Because with

```
SELECT *
FROM (
    SELECT name, type, COUNT(*)
    FROM main.treeitem
    GROUP BY name, type
) q
WHERE count > 1
ORDER BY type, name;
```

I have 200+ results...

**Comment by sbrunner** [comment]
I don't understand why you have some many duplicate thing do you have an know reason?

**Comment by rbovard** [comment]
What's the purpose of this constraint?

**Comment by rbovard** [comment]
> I don't understand why you have some many duplicate thing do you have an know reason?

Layers:
* Mostly desktop and mobile layers

Groups:
* There is some common group names like: batiments, zones, conduites, noeuds, etc.

**Comment by rbovard** [comment]
@gnerred @kalbermattenm 

Could you please tell me how many records you have with:

```
SELECT *
FROM (
    SELECT name, type, COUNT(*)
    FROM main.treeitem
    GROUP BY name, type
) q
WHERE count > 1
ORDER BY type, name;
```

**Comment by kalbermattenm** [comment]
Is does not return any result on our DB.... (empty table...)

**Comment by rbovard** [comment]
Mmm ok, it's probably because I get an error while upgrading db... (query on old structure)

**Comment by gnerred** [comment]
Same as Neuchâtel... @rbovard what you ask to try is the same as original sql, no ?

**Comment by rbovard** [comment]
@gnerred Yes and the last one without the where clause.

My concern is that I have some layers and groups with the same name, so the query

```
[SQL: 'ALTER TABLE main.treeitem ADD CONSTRAINT type_name_unique_treeitem UNIQUE (type, name)']
```

throws an error...

**Comment by gnerred** [comment]
Ok sorry. The request without the where clause returns a lot of rows. I have cleaned my DB to remane all dupplicate names (I did not have a lot), so I haven't this issue.

**Comment by kalbermattenm** [comment]
I also renamed all duplicate layers and groups.

You should wait for the next RC release, see https://github.com/camptocamp/c2cgeoportal/issues/2534#issuecomment-252162291

**Comment by rbovard** [comment]
Ok, thanks guys for the infos!

**Comment by rbovard** [comment]
@gnerred @kalbermattenm Be aware that the layer and group names are in permalinks, so be careful when renmming them...

**Comment by kalbermattenm** [comment]
I also need a solution for that (multiple layers having the same has to work).

I just renamed everything in order to be able to finalize the update, but I surely would like to revert that.

**Comment by gnerred** [comment]
Thanks @rbovard . From my side, I only had few test and non significant layers with dupplicate names.

**Comment by sbrunner** [comment]
> multiple layers having the same has to work

It miss a word, I agree with:
«multiple layers having the same **layer** has to work»
but not with:
«multiple layers having the same **name** has to work»
Because the name is the way to identify the element in the admin interface e.g. metadata...

One thing who is missing is a better way to migrate, the accrual situation isn't so good...

**Comment by rbovard** [comment]
So it's a big regression... At least for @kalbermattenm and I!

**Comment by sbrunner** [comment]
> So it's a big regression 

Where is the regression?

**Comment by rbovard** [comment]
Cannot have layers with the same name.

**Comment by sbrunner** [comment]
@rbovard Do you catch that I will add a layer column with the WMS layer name who it can contains multiple row with the same value?

**Comment by rbovard** [comment]
No sorry, I didn't...

But how do you want to handle the `UNIQUE CONSTRAINT` ?

**Comment by sbrunner** [comment]
The element of the tree should have a unique name per type, in the database it will me on the pair of columns type, name on the table treeitem.

**Comment by rbovard** [comment]
As I understand, we cannot anymore have 2 GMF layers of same type with same name but it's possible to use a same WMS layer via multiple GMF layers (with different name).

It nice but in this case we will loose all our concerned permalinks!

**Comment by rbovard** [comment]
After tests with permalinks in `2.1.0.rc4`, I noticed:
* Renamed layers are lost --> **KO**
* Renamed 1st level of groups are lost --> **KO**
* Renamed subgroups are not impacted --> OK

**Comment by rbovard** [comment]
@sbrunner Your workaround script `treeitem_uniquename.py` seems to be a good solution but when should it be executed?

Because when upgrading to `2.1.0.rc4`, I was stuck in step 4 because of dupplicates values `(type, name)` and I needed to manually rename my dupplicates to continue upgrade process (the value `name` was copied in `layer`).

**Comment by sbrunner** [comment]
> when should it be executed?

Here: https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl#L202

**Comment by sbrunner** [comment]
It looks that your on the wrong database, there isn't any layer with the name `tr_coupes` in the _v2 database ...

**Comment by rbovard** [comment]
Meanwhile I renamed dupplicates layer by hand to make my project work:

```
SELECT *
FROM main.treeitem
WHERE name LIKE 'tr_coupes%';
```

**Comment by sbrunner** [comment]
What's the status of this issue?

**Comment by rbovard** [comment]
I need to check the `treeitem_uniquename.py`on next attempt to migrate to 2.1 from 1.6 database, because I was bypassing this issue by renaming by hand dupplicated layers.

**Comment by sbrunner** [comment]
What's the status of this issue?
