### ISSUE TITLE
Error during upgrade to 2.1.0rc4

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2638]
```
ERROR: Unable to update the path 'checker.all', types '<type 'dict'>', '<type 'NoneType'>'.
ERROR: Unable to update the path 'checker.defaults', types '<type 'dict'>', '<type 'NoneType'>'.
Traceback (most recent call last):
  File ".build/venv/bin/c2c-template", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/c2c/template.py", line 185, in main
    _proceed(files, used_vars, options)
  File ".build/venv/local/lib/python2.7/site-packages/c2c/template.py", line 209, in _proceed
    bottle_template(files, used_vars, engine)
  File ".build/venv/local/lib/python2.7/site-packages/c2c/template.py", line 240, in bottle_template
    template, **used_vars
  File ".build/venv/bin/bottle.py", line 3609, in template
    return TEMPLATES[tplid].render(kwargs)
  File ".build/venv/bin/bottle.py", line 3280, in render
    return self.tpl.render(**_defaults)
  File ".build/venv/local/lib/python2.7/site-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File ".build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File ".build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File ".build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "project_yaml_mako", line 30, in render_body
  File ".build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 226, in __str__
    raise NameError("Undefined")
NameError: Undefined
CONST_Makefile:600: recipe for target 'project.yaml' failed
make: *** [project.yaml] Error 1
```

**Comment by sbrunner** [comment]
Your CONST_vars.yaml looks relay strange, the checker part should looks like this:
https://github.com/camptocamp/demo_geomapfish/blob/master/CONST_vars.yaml#L300-L349

**Comment by rbovard** [comment]
`CONST_*` are files that are handled by updates, I have no reason to edit them, right?

**Comment by sbrunner** [comment]
Normally yes, but I don't know how you get this file, then we should fix it to make the upgrade possible...

**Comment by rbovard** [comment]
Ok, strange...

FYI I was stuck in the middle of the last attempt to migrate to rc1, maybe it's related?

**Comment by sbrunner** [comment]
It's strange that in this commit there is only the CONST_changelog ...

**Comment by rbovard** [comment]
Like I said before, I was stuck in the middle of upgrade and commited what I could... Maybe something went wrong at this time.

Any idea of what I can do?

**Comment by sbrunner** [comment]
You try this https://github.com/camptocamp/c2cgeoportal/issues/2638#issuecomment-260655674?

**Comment by rbovard** [comment]
I copied the content of `# Checker configuration` and now I get:

```
WMTSCAPABILITIES_PATH=1.0.0/WMTSCapabilities-v2.xml INSTANCE_ID=v2 APACHE_ENTRY_POINT=/v2/ DOCKER_BASE=no DEVELOPMENT=TRUE PACKAGE=nyon .build/venv/bin/c2c-template --vars vars_nyon.yaml --engine mako --files project.yaml.mako
Traceback (most recent call last):
  File ".build/venv/bin/c2c-template", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/c2c/template.py", line 185, in main
    _proceed(files, used_vars, options)
  File ".build/venv/local/lib/python2.7/site-packages/c2c/template.py", line 209, in _proceed
    bottle_template(files, used_vars, engine)
  File ".build/venv/local/lib/python2.7/site-packages/c2c/template.py", line 240, in bottle_template
    template, **used_vars
  File ".build/venv/bin/bottle.py", line 3609, in template
    return TEMPLATES[tplid].render(kwargs)
  File ".build/venv/bin/bottle.py", line 3280, in render
    return self.tpl.render(**_defaults)
  File ".build/venv/local/lib/python2.7/site-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File ".build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File ".build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File ".build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "project_yaml_mako", line 30, in render_body
  File ".build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 226, in __str__
    raise NameError("Undefined")
NameError: Undefined
CONST_Makefile:600: recipe for target 'project.yaml' failed
make: *** [project.yaml] Error 1
```

**Comment by sbrunner** [comment]
It seem that you use `${host}` in the `project.yaml.mako` file that not defined in the vars files...

**Comment by rbovard** [comment]
I'm a little lost with all this variables substitutions... Can I get this one: https://github.com/camptocamp/nyon_c2cgeoportal/blob/v2/instance_v2.mk#L3?

**Comment by rbovard** [comment]
I removed it following because of that: https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl#L132

Should I remove it from my `project.yaml.mako`?

**Comment by rbovard** [comment]
I tried to remove it and it worked...

Now I get that on `upgrade1`:

```
make[1]: *** No rule to make target 'CONST_versions.txt', needed by '.build/requirements.timestamp'.  Stop.
make[1]: Leaving directory '/var/www/vhosts/nyon-geoportail/private/v2'
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 98, in main
    c2ctool.upgrade()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 216, in upgrade
    self.step1()
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 339, in step1
    check_call(["make", "-f", self.options.file, ".build/requirements.timestamp"])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'instance_v2.mk', '.build/requirements.timestamp']' returned non-zero exit status 2
CONST_Makefile:1179: recipe for target 'upgrade1' failed
make: *** [upgrade1] Error 1
```

**Comment by rbovard** [comment]
It's really too messy here, I'll start the upgrade from the beginning...
