### ISSUE TITLE
Error in step 1 upgrading to rc4

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2643]
Hmmm.... I do not get it... It is `make` which fails at the `pot-create` step, but I do not get why... ??

```
C:\git_projects\sitn_c2cgeoportal>make -f michael.mk build
.build/venv/Scripts/pot-create --config lingua-client.cfg --output sitn/locale/sitn-client.pot sitn/templates/admin_add_
user.html sitn/templates/airpages/ipc.html sitn/templates/airpages/meteodataquery.html sitn/templates/api/apidocs/map.ht
ml sitn/templates/api/apidocs/searchbox.html sitn/templates/api/apidocs/xmap.html sitn/templates/api/apihelp.html sitn/t
emplates/api/indexAPI.html sitn/templates/api/sapi/apiexamples.html sitn/templates/api/sapi/sapitutorial.html sitn/templ
ates/api/SITNlicensing.html sitn/templates/api/xapi/xapiexamples.html sitn/templates/api/xapi/xapitutorial.html sitn/tem
plates/api/xapihelp.html sitn/templates/data_templates/cadsout_disclaimer.html sitn/templates/data_templates/cadsout_met
adata.html sitn/templates/data_templates/cadsout_photo.html sitn/templates/data_templates/controlling_geoshop.html sitn/
templates/data_templates/controlling_syncserver.html sitn/templates/data_templates/di01_hydrants_intranet.html sitn/temp
lates/data_templates/di06_sites_opam.html sitn/templates/data_templates/di07_opam_prod_chimiques.html sitn/templates/dat
a_templates/di09_opam_responsable.html sitn/templates/data_templates/di10_opam_genre_activite.html sitn/templates/data_t
emplates/di11_opam_prod_stock.html sitn/templates/data_templates/dn_reports.html sitn/templates/data_templates/ecomorpho
logie.html sitn/templates/data_templates/eg10_panneaux_bati_pv.html sitn/templates/data_templates/eg11_panneaux_face_pv.
html sitn/templates/data_templates/eg13_panneaux_face_toit_thermique.html sitn/templates/data_templates/en12_citbru_auto
risations.html sitn/templates/data_templates/en13_citbru_locaux_citernes.html sitn/templates/data_templates/en14_citbru_
locaux_chauffage.html sitn/templates/data_templates/en19_citbru_reservoirs.html sitn/templates/data_templates/en20_citbr
u_citernes.html sitn/templates/data_templates/en21_citbru_chauffages.html sitn/templates/data_templates/en_citbru_rappor
ts.html sitn/templates/data_templates/en_citbru_repondant.html sitn/templates/data_templates/fo10_unite_gestion_pgi.html
 sitn/templates/data_templates/geone_details_affaire.html sitn/templates/data_templates/geone_parcelles_deposees.html si
tn/templates/data_templates/geone_parcelles_rf.html sitn/templates/data_templates/hy06_points_injection.html sitn/templa
tes/data_templates/hy12_reapparition.html sitn/templates/data_templates/infolica_check_terris.html sitn/templates/data_t
emplates/metadata.html sitn/templates/data_templates/metadata_show.html sitn/templates/data_templates/orthophoto_lubis.h
tml sitn/templates/data_templates/pa01_recensement_archi.html sitn/templates/data_templates/pa02_patrimoine_archi.html s
itn/templates/data_templates/patri_immo_etat_detail.html sitn/templates/data_templates/po01_cicop.html sitn/templates/da
ta_templates/prop_etat_suivi_print.html sitn/templates/data_templates/sante_defi_add.html sitn/templates/data_templates/
sat_suivi_print.html sitn/templates/data_templates/st01_defibillateur.html sitn/templates/data_templates/st03_contact_ur
gence.html sitn/templates/data_templates/tc04_ruchers_list.html sitn/templates/data_templates/traffic_event_show.html si
tn/templates/data_templates/users_layer_list.html sitn/templates/data_templates/vt10_parcelles_viticoles.html sitn/templ
ates/data_templates/vt8_sols.html sitn/templates/data_templates/waterquality_ex11.html sitn/templates/data_templates/wat
erquality_qlt_city_ne.html sitn/templates/data_templates/waterquality_qlt_lakes.html sitn/templates/data_templates/water
quality_qlt_subsurf.html sitn/templates/data_templates/waterquality_qlt_surf.html sitn/templates/desktop.html sitn/templ
ates/help_templates/help.html sitn/templates/help_templates/help_contact.html sitn/templates/help_templates/help_extract
.html sitn/templates/help_templates/help_faq.html sitn/templates/help_templates/help_header.html sitn/templates/help_tem
plates/help_webservices.html sitn/templates/mobile.html sitn/templates/owner.html sitn/templates/search-tip.html sitn/st
atic-ngeo/js/desktop.js sitn/static-ngeo/js/mobile.js sitn/static-ngeo/js/sitnmodule.js    .build/config.yaml developmen
t.ini
Error parsing .\sitn/templates/airpages/ipc.html at line 47 column 126
Error parsing .\sitn/templates/api/apihelp.html at line 15 column 41
Error parsing .\sitn/templates/api/sapi/apiexamples.html at line 15 column 41
Error parsing .\sitn/templates/api/xapi/xapiexamples.html at line 15 column 41
Error parsing .\sitn/templates/api/xapihelp.html at line 15 column 41
Error parsing .\sitn/templates/data_templates/cadsout_metadata.html at line 6 column 36
Error parsing .\sitn/templates/data_templates/controlling_syncserver.html at line 125 column 40
Error parsing .\sitn/templates/data_templates/metadata.html at line 5 column 44
Error parsing .\sitn/templates/data_templates/traffic_event_show.html at line 14 column 2
Error parsing .\sitn/templates/desktop.html at line 6 column 74
Error parsing .\sitn/templates/help_templates/help_extract.html at line 30 column 41
Error parsing .\sitn/templates/mobile.html at line 6 column 2
Error parsing .\sitn/templates/owner.html at line 2 column 1
No handlers could be found for logger "c2cgeoportal.pyramid_"
Get DescribeFeatureType for url: http://localhost/michael/mapserv?VERSION=1.1.0&REQUEST=DescribeFeatureType&SERVICE=WFS
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\pot-create.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\lingua\extract.py", line 330, in main
    for message in extractor(real_filename, options):
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\lingua_extractor.py", line 211,
 in __call__
    self._import(LayerWMTS, messages, self._import_layer_wmts)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\lingua_extractor.py", line 233,
 in _import
    for item in items:
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 90, in instance
s
    util.raise_from_cause(err)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_f
rom_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 75, in instance
s
    rows = [proc(row) for row in fetch]
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 631, in polymor
phic_instance
    return instance_fn(row)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 437, in _instan
ce
    loaded_instance, populate_existing, populators)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 498, in _popula
te_full
    dict_[key] = getter(row)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1400, in proce
ss
    value = self._object_value_for_elem(value)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1317, in _obje
ct_value_for_elem
    '"%s" is not among the defined enum values' % elem)
LookupError: "image/jpg" is not among the defined enum values
CONST_Makefile:701: recipe for target 'sitn/locale/sitn-client.pot' failed
make: *** [sitn/locale/sitn-client.pot] Error 1
```

**Comment by sbrunner** [comment]
This is a new check of sqlalchemy.
In a WMTS layer It seem that you have an image_type as 'image/jpg' and it's not allowed it should be 'image/jpeg'.

**Comment by kalbermattenm** [comment]
+1... But I do not get why this is happening in Lingua... ;-)

**Comment by sbrunner** [comment]
Because lingua do some call on the database to fetch the concerned strings :-)
