### ISSUE TITLE
Error on upgrade step 4 with lingua_extractor

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2661]
* [x] I am using the latest minor version of the major version (`x.y.last`)

For commiters:

* [ ] I have assigned a blue and a green label
* [ ] I have assigned a milestone

Project:

* GitHub URL:
* Infrastructure description URL:
* Host:
* GeoMapFish version: 2.1.0.rc4

Running command: ` make -f instance_v2.mk upgrade4`

Result:

```
.build/venv/bin/pot-create --config lingua-client.cfg --output nyon/locale/nyon-client.pot nyon/templates/edit.html nyon/templates/desktop.html nyon/templates/routing.html nyon/templates/api/apihelp_old.html nyon/templates/api/xapihelp.html nyon/templates/api/apihelp.html nyon/templates/mobile.html nyon/static-ngeo/js/nyonmodule.js nyon/static-ngeo/js/mobile.js    .build/config.yaml development.ini
Traceback (most recent call last):
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/lib/lingua_extractor.py", line 126, in __call__
    exit()
  File "v2/.build/venv/lib/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: None

Traceback (most recent call last):
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/lib/lingua_extractor.py", line 126, in __call__
    exit()
  File "v2/.build/venv/lib/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: None

Error parsing ./nyon/templates/desktop.html at line 3 column 102
Traceback (most recent call last):
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/lib/lingua_extractor.py", line 126, in __call__
    exit()
  File "v2/.build/venv/lib/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: None

Traceback (most recent call last):
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/lib/lingua_extractor.py", line 126, in __call__
    exit()
  File "v2/.build/venv/lib/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: None

Traceback (most recent call last):
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/lib/lingua_extractor.py", line 126, in __call__
    exit()
  File "v2/.build/venv/lib/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: None

Traceback (most recent call last):
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/lib/lingua_extractor.py", line 126, in __call__
    exit()
  File "v2/.build/venv/lib/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: None

Traceback (most recent call last):
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/lib/lingua_extractor.py", line 126, in __call__
    exit()
  File "v2/.build/venv/lib/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: None

Error parsing ./nyon/templates/mobile.html at line 6 column 74
No handlers could be found for logger "c2cgeoportal.pyramid_"
# removes the always changed date line
sed -i '/^"POT-Creation-Date: /d' nyon/locale/nyon-client.pot
sed -i '/^"PO-Revision-Date: /d' nyon/locale/nyon-client.pot
chmod go+r nyon/locale/nyon-client.pot
mkdir -p nyon/locale/fr/LC_MESSAGES/
[ -f nyon/locale/fr/LC_MESSAGES/nyon-client.po ] || msginit --no-translator --input=nyon/locale/nyon-client.pot --output-file=nyon/locale/fr/LC_MESSAGES/nyon-client.po -l fr
touch --no-create nyon/locale/fr/LC_MESSAGES/nyon-client.po
msgmerge --backup=none --update --sort-output --no-location nyon/locale/fr/LC_MESSAGES/nyon-client.po nyon/locale/nyon-client.pot
................................................................... done.
```

If no direct error, result and expected result:

**Comment by sbrunner** [comment]
Will be fixed by https://github.com/camptocamp/c2cgeoportal/pull/2658
