### ISSUE TITLE
Problem during install of 2.1.0rc7 - elevationLayersConfig 

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2755]
In step 4 I have the following problem : 

`make -f v2.mk upgrade4`

```
info ol Parsing dependencies
info ol Compiling 506 sources
ERR! compile /var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/cartoriviera/static-ngeo/js/mobile.js:43: ERROR - assignment to property elevationLayersConfig of cartoriviera.MobileController
ERR! compile found   : {
ERR! compile   mns: {unit: string},
ERR! compile   mnt: {unit: string},
ERR! compile   rayglobal: {unit: string}
ERR! compile }
ERR! compile required: (Array<string>|null)
ERR! compile   this.elevationLayersConfig = {
ERR! compile   ^
ERR! compile
ERR! compile
ERR! compile 1
ERR! compile  error(s), 0 warning(s),
ERR! compile 96.8%
ERR! compile  typed
ERR! compile
ERR! Process exited with non-zero status, see log for more detail: 1
CONST_Makefile:884: recipe for target '.build/mobile.js' failed
make[1]: *** [.build/mobile.js] Error 1
make[1]: Leaving directory '/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish'
Traceback (most recent call last):
  File ".build/venv/bin/c2ctool", line 11, in <module>
    sys.exit(main())
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 100, in main
    c2ctool.upgrade()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 231, in upgrade
    self.step4()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish_v2/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/c2ctool.py", line 452, in step4
    check_call(["make", "-f", self.options.file, "build"])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'v2.mk', 'build']' returned non-zero exit status 2
CONST_Makefile:1261: recipe for target 'upgrade4' failed
make: *** [upgrade4] Error 1
```

**Comment by sbrunner** [comment]
Do you update your configuration like this?
https://github.com/camptocamp/ngeo/pull/2179/files#diff-8616751e05d1e98bb60fb27f194ce104

**Comment by gnerred** [comment]
I applied the changes of the ngeo.diff, but forgot a line, sorry... Now it is OK :O)

**Comment by sbrunner** [comment]
nice :-)

**Comment by gnerred** [comment]
This version 2.1.0rc7 seems to be a good version, it seems that I have no more blocking issue and the install procedure ran without problem. But I still have to do more intensive tests.
