### ISSUE TITLE
OGC Proxy is gone?

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2852]
Is OGC Proxy gone? Because after upgrade to `2.1.2.dev1` I get this error:

```
MakoRenderingException: 

Traceback (most recent call last):
  File ".build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File ".build/venv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File ".build/venv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File ".build/venv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File ".build/venv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "nyon/templates/desktop.js", line 16, in render_body
    OpenLayers.ProxyHost = "${request.route_url('ogcproxy') | n}?url=";
  File ".build/venv/lib/python2.7/site-packages/pyramid/url.py", line 266, in route_url
    raise KeyError('No such route named %s' % route_name)
KeyError: 'No such route named ogcproxy'
```

Full stack:

```
File '.build/venv/lib/python2.7/site-packages/weberror/evalexception.py', line 429 in respond
  app_iter = self.application(environ, detect_start_response)
File '.build/venv/lib/python2.7/site-packages/fanstatic/publisher.py', line 219 in __call__
  return self.app(environ, start_response)
File '.build/venv/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '.build/venv/lib/python2.7/site-packages/webob/request.py', line 1299 in send
  application, catch_exc_info=False)
File '.build/venv/lib/python2.7/site-packages/webob/request.py', line 1263 in call_application
  app_iter = application(self.environ, start_response)
File '.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 223 in __call__
  response = self.invoke_subrequest(request, use_tweens=True)
File '.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 198 in invoke_subrequest
  response = handle_request(request)
File '.build/venv/lib/python2.7/site-packages/c2cgeoportal/lib/cacheversion.py', line 62 in __call__
  response = self.handler(request)
File '.build/venv/lib/python2.7/site-packages/pyramid/tweens.py', line 20 in excview_tween
  response = handler(request)
File '.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 119 in tm_tween
  reraise(*exc_info)
File '.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 98 in tm_tween
  response = handler(request)
File '.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 145 in handle_request
  view_name
File '.build/venv/lib/python2.7/site-packages/pyramid/view.py', line 541 in _call_view
  response = view_callable(context, request)
File '.build/venv/lib/python2.7/site-packages/c2cgeoportal/pyramid_.py', line 120 in new_f
  return f(root, request)
File '.build/venv/lib/python2.7/site-packages/pyramid/config/views.py', line 377 in rendered_view
  context)
File '.build/venv/lib/python2.7/site-packages/pyramid/renderers.py', line 450 in render_view
  return self.render_to_response(response, system, request=request)
File '.build/venv/lib/python2.7/site-packages/pyramid/renderers.py', line 473 in render_to_response
  result = self.render(value, system_values, request=request)
File '.build/venv/lib/python2.7/site-packages/pyramid/renderers.py', line 469 in render
  result = renderer(value, system_values)
File '.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py', line 156 in __call__
  reraise(MakoRenderingException(errtext), None, exc_info[2])
File '.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py', line 148 in __call__
  result = template.render_unicode(**system)
File '.build/venv/lib/python2.7/site-packages/mako/template.py', line 471 in render_unicode
  as_unicode=True)
File '.build/venv/lib/python2.7/site-packages/mako/runtime.py', line 838 in _render
  **_kwargs_for_callable(callable_, data))
File '.build/venv/lib/python2.7/site-packages/mako/runtime.py', line 873 in _render_context
  _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File '.build/venv/lib/python2.7/site-packages/mako/runtime.py', line 899 in _exec_template
  callable_(context, *args, **kwargs)
File '_desktop_js', line 43 in render_body
File '.build/venv/lib/python2.7/site-packages/pyramid/url.py', line 266 in route_url
  raise KeyError('No such route named %s' % route_name)
```

**Comment by rbovard** [comment]
I found that in the doc:

> The OGC proxy is deprecated because with modern browsers it is not required anymore.

Okay but now the WMS Browser doesn't work anymore without the OGC proxy:

```
XMLHttpRequest cannot load https://wms.geo.admin.ch/
Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.
```

Is there something to do to allow this host?

**Comment by rbovard** [comment]
I have a similar issue with an external WMTS layer `asitvd.fond_pourortho`:

```
XMLHttpRequest cannot load https://ows.asitvd.ch/wmts/1.0.0/WMTSCapabilities.xml.
Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by sbrunner** [comment]
You speak about the CGXP application?
If yes the simpler way is to re-enable it: 
http://camptocamp.github.io/c2cgeoportal/2.1/integrator/security.html#enable-disable-the-ogc-proxy

**Comment by rbovard** [comment]
It's what I've done yesterday and I get this error:

```
Traceback (most recent call last):
  File "v2/.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "v2/.build/venv/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "v2/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "v2/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "v2/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "v2/nyon/templates/desktop.js", line 16, in render_body
    OpenLayers.ProxyHost = "${request.route_url('ogcproxy') | n}?url=";
  File "v2/.build/venv/lib/python2.7/site-packages/pyramid/url.py", line 266, in route_url
    raise KeyError('No such route named %s' % route_name)
KeyError: 'No such route named ogcproxy'
```

The changes I made:

```
diff --git a/nyon/templates/desktop.js b/nyon/templates/desktop.js
index 352d1e1..09d0f71 100644
--- a/nyon/templates/desktop.js
+++ b/nyon/templates/desktop.js
@@ -13,6 +13,7 @@ Ext.onReady(
         OpenLayers.DOTS_PER_INCH = 72;
+        OpenLayers.ProxyHost = "${request.route_url('ogcproxy') | n}?url=";
         OpenLayers.ImgPath = "${request.static_url('nyon:static/lib/cgxp/core/src/theme/img/ol/') | n}";

diff --git a/vars_nyon.yaml b/vars_nyon.yaml
index 0dcacf4..9072d8b 100644
--- a/vars_nyon.yaml
+++ b/vars_nyon.yaml
@@ -258,6 +258,9 @@ vars:

+    # OGC proxy
+    ogcproxy_enable: true
+
 update_paths:
```

**Comment by sbrunner** [comment]
Can you try to apply this?
https://github.com/camptocamp/c2cgeoportal/commit/0ed3cbe1a7527a4608b85652fc3c28ac8e623afc

**Comment by rbovard** [comment]
```
.build/venv/bin/pot-create --config lingua-client.cfg --output nyon/locale/nyon-client.pot nyon/templates/mobile.html nyon/static-ngeo/js/nyonmodule.js nyon/static-ngeo/js/mobile.js   nyon/static-ngeo/components/contextualdata/contextualdata.html .build/config.yaml development.ini
Traceback (most recent call last):
  File ".build/venv/bin/pot-create", line 11, in <module>
    sys.exit(main())
  File "v2/.build/venv/local/lib/python2.7/site-packages/lingua/extract.py", line 330, in main
    for message in extractor(real_filename, options):
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/lib/lingua_extractor.py", line 211, in __call__
    self.env = bootstrap(filename)
  File "v2/.build/venv/local/lib/python2.7/site-packages/pyramid/paster.py", line 131, in bootstrap
    app = get_app(config_uri, options=options)
  File "v2/.build/venv/local/lib/python2.7/site-packages/pyramid/paster.py", line 31, in get_app
    global_conf=options)
  File "v2/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "v2/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "v2/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "v2/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 203, in invoke
    app = context.app_context.create()
  File "v2/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "v2/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "v2/.build/venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "v2/nyon/__init__.py", line 18, in main
    config.include("c2cgeoportal")
  File "v2/.build/venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 798, in include
    c(configurator)
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/__init__.py", line 55, in includeme
    includeme(config)
  File "v2/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/pyramid_.py", line 502, in includeme
    config.add_view("papyrus_ogcproxy.views:ogcproxy", route_name="ogcproxy")
  File "v2/.build/venv/local/lib/python2.7/site-packages/pyramid/util.py", line 519, in wrapper
    view = self.maybe_dotted(view)
  File "v2/.build/venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 869, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "v2/.build/venv/local/lib/python2.7/site-packages/pyramid/path.py", line 320, in maybe_resolve
    return self._resolve(dotted, package)
  File "v2/.build/venv/local/lib/python2.7/site-packages/pyramid/path.py", line 325, in _resolve
    return self._pkg_resources_style(dotted, package)
  File "v2/.build/venv/local/lib/python2.7/site-packages/pyramid/path.py", line 345, in _pkg_resources_style
    return ep.resolve()  # pragma: NO COVER
  File "v2/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named papyrus_ogcproxy.views
CONST_Makefile:710: recipe for target 'nyon/locale/nyon-client.pot' failed
make: *** [nyon/locale/nyon-client.pot] Error 1
```

**Comment by sbrunner** [comment]
You should also add the ``papyrus_ogcproxy`` package in the ``install_requires`` of the ``setup.py`` file :-)

**Comment by rbovard** [comment]
It's working, thanks.

**Comment by sbrunner** [comment]
Cool, sorry for long interaction :-)
