### ISSUE TITLE
Upgrading to 2.3.1.dev1

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2889]
During the first step (`make -f michael.mk upgrade1`), I get the here under error... Any hint ?

```
.build/venv/Scripts/c2c-template --vars vars_sitn_localdev.yaml --engine mako --files CONST_create_template/deploy/deplo
y.cfg.mako
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\c2c-template.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2c\template.py", line 213, in main
    _proceed(files, used_vars, options)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2c\template.py", line 237, in _proceed
    bottle_template(files, used_vars, engine)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2c\template.py", line 268, in bottle_template
    template, **used_vars
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\scripts\bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\scripts\bottle.py", line 3290, in render
    return self.tpl.render(**_defaults)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "CONST_create_template_deploy_deploy_cfg_mako", line 28, in render_body
TypeError: 'Undefined' object has no attribute '__getitem__'
CONST_Makefile:662: recipe for target 'CONST_create_template/deploy/deploy.cfg' failed
make: *** [CONST_create_template/deploy/deploy.cfg] Error 1
```

**Comment by kalbermattenm** [comment]
Wait... I think I found what is missing....

**Comment by kalbermattenm** [comment]
OK, I first just deleted the deploy folder in CONST_create_template, but that was not a good idea...

Finally I just applied https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/scaffolds/update/CONST_CHANGELOG.txt_tmpl#L14-L15 to make it work...
