### ISSUE TITLE
Error with WMTSCapabilities path with S3 storage

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2934]
After a `cleanall` on `2.1.2`, I have an issue on build with the WMTSCapabilities generation.

* Commands:

```
make -f instance_v2.mk cleanall
make -f instance_v2.mk build
```

* Result:

```
.build/venv/bin/generate_controller --capabilities
Traceback (most recent call last):
  File ".build/venv/bin/generate_controller", line 11, in <module>
    sys.exit(main())
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud_chain/controller.py", line 82, in main
    _generate_wmts_capabilities(gene)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud_chain/controller.py", line 200, in _generate_wmts_capabilities
    _send(capabilities, cache['wmtscapabilities_file'], 'application/xml', cache)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud_chain/controller.py", line 101, in _send
    s3key.put()
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud/lib/s3.py", line 134, in put
    return self.bucket.put(self.name, self.headers, self.body)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud/lib/s3.py", line 194, in put
    return self.connection.put(self.name, '/' + key_name, headers, body)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud/lib/s3.py", line 289, in put
    return self.request('PUT', bucket_name, url, body=body, headers=headers)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud/lib/s3.py", line 309, in request
    raise S3Error(method, url, body, headers, response)
tilecloud.lib.s3.S3Error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
CONST_Makefile:1322: recipe for target '/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml' failed
make: *** [/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml] Error 1
```

In fact, the path `/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml` is wrong since it should be on S3 and not in local storage.

The migration to S3 storage was done in `1.6` and config ported to `2.1`, anyway I made a cleanall on `1.6` and a build, it works fine.

* Commands:

```
make -f instance_dev.mk cleanall
make -f instance_dev.mk build
```

* Result:

```
.build/venv/bin/generate_controller --capabilities
```

Did something about WMTSCapabilities generation has changed between `1.6` and `2.1`?

**Comment by rbovard** [comment]
For the record, I have my `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` correctly defined in `secure.mk` in both instances.

**Comment by rbovard** [comment]
@sbrunner Do you have a workaround I want to test?

**Comment by sbrunner** [comment]
To debug it I need your AWS credentials ...

**Comment by rbovard** [comment]
See `/var/www/vhosts/nyon-geoportail/private/v2/secure.mk`

PS: Be careful when debugging, the tiles are used in prod.

**Comment by sbrunner** [comment]
Thanks :-)

Yes :-)

**Comment by sbrunner** [comment]
I didn't change anything and it's working ...

**Comment by rbovard** [comment]
Strange...

You did the equivalent of:

```
make -f instance_v2.mk cleanall
make -f instance_v2.mk build
```

**Comment by rbovard** [comment]
I just wanted to retry but I have an other issue:

```
node_modules/.bin/npm install || sleep 20 || node_modules/.bin/npm install || sleep 90 || node_modules/.bin/npm install
npm WARN npm npm does not support Node.js v0.10.29
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'
```

Is it working for you?

**Comment by sbrunner** [comment]
I don't know how it was working before because you have a too old node version, node >= 4 is required ...

**Comment by rbovard** [comment]
What's going on? It was working when I opened this issue (execpt the WMTSCapabilities generation) and I didn't change anything since then...

**Comment by sbrunner** [comment]
I don't know but It's sure that you needs node version 4 or version 6 :-), You should ask it to the sysadmins ...

**Comment by rbovard** [comment]
@yjacolin did you changed something?

**Comment by yjacolin** [comment]
nope I didn't change anything but I have the same issue in another instance. We can debug easily as the tiles are not in production!

**Comment by yjacolin** [comment]
All is working correctly in my project (another customer). No npm issue or the first in this issue (the one I get sooner this afternoon).

**Comment by rbovard** [comment]
The issue is still here and I don't understand because I didn't change anything in my project...

@sbrunner How can I fix this node version?

**Comment by sbrunner** [comment]
Ask to the sysadmins :-)

**Comment by yjacolin** [comment]
@rbovard I take the leadership on this (i.e. create a ticket in our jira infrastructure and follow it)

**Comment by rbovard** [comment]
@yjacolin Okay, thanks.

@sbrunner Please keep this issue open, I'd like to be sure that's WMTS is working as you said.

**Comment by rbovard** [comment]
The nodejs is solved (see #2959)

@sbrunner I still have my original issue.

To be sure, I did a cleanallcache before but the result is the same:

```
tilecloud.lib.s3.S3Error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
CONST_Makefile:1322: recipe for target '/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml' failed
```

**Comment by rbovard** [comment]
And as I said in my original post:

> In fact, the path `/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml` is wrong since it should be on S3 and not in local storage.

I think this is the issue, no?

**Comment by yjacolin** [comment]
"/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml" is a dynamic target name in the CONST_Makefile, not sure that it tries to build such path.

Could you confirm that the command line is working by hand: `.build/env/bin/generate_controller --capabilities` (check the path before to run it)

**Comment by rbovard** [comment]
```
$ .build/venv/bin/generate_controller --capabilities
Traceback (most recent call last):
  File ".build/venv/bin/generate_controller", line 11, in <module>
    sys.exit(main())
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud_chain/controller.py", line 82, in main
    _generate_wmts_capabilities(gene)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud_chain/controller.py", line 200, in _generate_wmts_capabilities
    _send(capabilities, cache['wmtscapabilities_file'], 'application/xml', cache)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud_chain/controller.py", line 101, in _send
    s3key.put()
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud/lib/s3.py", line 134, in put
    return self.bucket.put(self.name, self.headers, self.body)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud/lib/s3.py", line 194, in put
    return self.connection.put(self.name, '/' + key_name, headers, body)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud/lib/s3.py", line 289, in put
    return self.request('PUT', bucket_name, url, body=body, headers=headers)
  File "/var/www/vhosts/nyon-geoportail/private/v2/.build/venv/local/lib/python2.7/site-packages/tilecloud/lib/s3.py", line 309, in request
    raise S3Error(method, url, body, headers, response)
tilecloud.lib.s3.S3Error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
```

**Comment by rbovard** [comment]
And like I *also* said in my original post, the build was working after S3 config and suddenly not anymore.

Is there something related to the server management with Puppet?

**Comment by rbovard** [comment]
> "/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml" is a dynamic target name in the CONST_Makefile, not sure that it tries to build such path.

Are you sure? See https://github.com/camptocamp/nyon_c2cgeoportal/blob/v2/CONST_Makefile#L102

**Comment by sbrunner** [comment]
Yes but it's for a locale cache...

**Comment by rbovard** [comment]
Mmmh ok, so why this error  `CONST_Makefile:1322: recipe for target '/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml' failed`?

**Comment by yjacolin** [comment]
My guess is that the command line for this target is not working as you showed it yesterday. We already check the API Key last week but I want to check it again why/if this api key is not working anymore.

**Comment by yjacolin** [comment]
The version of Tilecloud should be 0.4.0, the installed is 0.3.0. The project configuration seems cleaned. @sbrunner any idea why the version is not correct?

**Comment by sbrunner** [comment]
Why it should be 0.4?

**Comment by yjacolin** [comment]
The issue come from "CONST_optional-requirements.txt" which ask for 0.3.0 and the Makefile has the following:
```
[..]v2$ grep ^tilecloud== CONST_optional-requirements.txt --colour=never
tilecloud==0.3.0
```
Workaround: change CONST_optional-requirements.txt to 0.4.0 in your project

@sbrunner could you upgrade this file in the c2cgeoportal project?

**Comment by rbovard** [comment]
See https://github.com/camptocamp/nyon_c2cgeoportal/pull/666/files#diff-7cf4959bb04e5b984ecb91d105bf089eR61

**Comment by yjacolin** [comment]
0.4 is needed to push tiles into Exoscale Objects storage.

**Comment by sbrunner** [comment]
OK then we should update it :-)

**Comment by rbovard** [comment]
Yes please...

**Comment by rbovard** [comment]
@yjacolin I still have some issues to build project build with WMTS SOS.

FYI I set manually `tilecloud==0.4.0` because I had the famous error:

```
tilecloud.lib.s3.S3Error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
CONST_Makefile:1322: recipe for target '/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml' failed
```

but now I get:

```
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
CONST_Makefile:1322: recipe for target '/var/sig/tiles/1.0.0/WMTSCapabilities-v2.xml' failed
```

Is it related to tilecloud version or SOS config?

**Comment by rbovard** [comment]
@yjacolin Any news on this one?

Because even with

```
tilecloud==0.4.0
tilecloud-chain==1.3.0
```

and `signature_version = s3` in `$HOME/.aws/config`

It still doesn't work:

```
ERROR:tilecloud_chain:__call__:Error in tile: 18/0/8, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/0/9, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/0/10, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/0/11, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/0/12, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/0/13, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/0/14, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/0/15, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/1/8, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/1/9, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
ERROR:tilecloud_chain:__call__:Error in tile: 18/1/10, ClientError(u'An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.',)
Traceback (most recent call last):
  File ".build/venv/bin/generate_tiles", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/tilecloud_chain/generate.py", line 433, in main
    generate.gene(options, gene, options.layer)
  File ".build/venv/local/lib/python2.7/site-packages/tilecloud_chain/generate.py", line 45, in gene
    self._gene(options, gene, layer, dimensions)
  File ".build/venv/local/lib/python2.7/site-packages/tilecloud_chain/generate.py", line 300, in _gene
    gene.consume()
  File ".build/venv/local/lib/python2.7/site-packages/tilecloud_chain/__init__.py", line 973, in consume
    consume(self.tilestream, test)
  File ".build/venv/local/lib/python2.7/site-packages/tilecloud/__init__.py", line 25, in consume
    collections.deque(iterator, maxlen=0)
  File ".build/venv/local/lib/python2.7/site-packages/tilecloud/filter/error.py", line 63, in __call__
    raise TooManyErrors
tilecloud.filter.error.TooManyErrors
```

**Comment by ochriste** [comment]
il me semble qu'il y a un problème avec le certificat ssl sur le serveur, je vais regarder ca avec un de nos sysadmin

**Comment by ochriste** [comment]
fausse piste

par contre il va falloir envisager de mettre a jour le certificat ssl:

`The certificate used to load https://map.nyon.ch/ uses an SSL certificate that will be distrusted in an upcoming release of Chrome. Once distrusted, users will be prevented from loading this resource. See https://g.co/chrome/symantecpkicerts for more information.`

est-ce que le certificat a été géré par Camptocamp ou bien cela a-t-il été fait de votre coté ?

**Comment by ochriste** [comment]
j'aimerais faire un test de generation de tiles,

est-ce que tu aurais un layer que je pourrais tester sans que cela pose problème pour la production actuelle ?

**Comment by rbovard** [comment]
All tiles are used in PROD but you can try with this command:

```
sudo -u www-data AWS_ACCESS_KEY_ID=<id> AWS_SECRET_ACCESS_KEY=<key> .build/venv/bin/generate_tiles --layer plan_cadastral --zoom 18
```

Be aware of that https://github.com/camptocamp/tilecloud-chain/issues/312 and get my https://github.com/camptocamp/nyon_c2cgeoportal/blob/master/secure.mk (in dev instance)

**Comment by rbovard** [comment]
@ochriste Did you managed to test it?

**Comment by ochriste** [comment]
no sorry, I was handling some urgent task, I may have some time tomorrow or friday

**Comment by rbovard** [comment]
Ok, that's fine.

FYI I created an issue on Jira GEO-816, but we should keep this one opened for the moment.

**Comment by sbrunner** [comment]
Moved to JIRA -> close :-)
