### ISSUE TITLE
2.1.4 to 2.2.0rc2 - pykwalify 

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#2986]
I am trying to install 2.2.0.dev2.

In the first upgrade step, I get the error described here under.

I (almost) get what `pykwalify` is trying to do, but I do not get how I am supposed to resolve the error... ?

Moreover, at SITN, we have plenty YAML vars which are not described in `CONST_config-schema.yaml`...

Any hint ?

```
C:\git_projects\sitn_c2cgeoportal>.build\venv\Scripts\pykwalify --data-file .build\_config.yaml --schema-file CONST_config-schema.yaml
 ERROR - validation.invalid
 ERROR -  --- All found errors ---
 ERROR - [u"Key 'satac_localisation' was not defined. Path: '/vars/checker/defaults'", u"Key 'satac_interrogation' was not defined. Path: '/vars/checker/defaults'", u"Key 'water_protection_areas' was not defined. Path: '/vars/checker/defaults'", u"Value '' is not a dict. Value path: '/vars/reset_password'", u"Cannot find required key 'base_url'. Path: '/vars/shortener'", u"Key 'length' was not defined. Path: '/vars/shortener'", u"required.novalue : '/vars/functionalities/registered'"]
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\pykwalify.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pykwalify\cli.py", line 95, in cli_entrypoint
    run(parse_cli())
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pykwalify\cli.py", line 82, in run
    c.validate()
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\pykwalify\core.py", line 176, in validate
    error_msg=u'.\n - '.join(self.validation_errors)))
pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
 - Key 'satac_localisation' was not defined. Path: '/vars/checker/defaults'.
 - Key 'satac_interrogation' was not defined. Path: '/vars/checker/defaults'.
 - Key 'water_protection_areas' was not defined. Path: '/vars/checker/defaults'.
 - Value '' is not a dict. Value path: '/vars/reset_password'.
 - Cannot find required key 'base_url'. Path: '/vars/shortener'.
 - Key 'length' was not defined. Path: '/vars/shortener'.
 - required.novalue : '/vars/functionalities/registered'.: Path: '/'>
```

**Comment by sbrunner** [comment]
It's looks that you have some errors int your vars files:
e.g. `/vars/checker/defaults/satac_localisation` shouldn't exists...

**Comment by kalbermattenm** [comment]
OK... I get it for like `- Key 'length' was not defined. Path: '/vars/shortener'.`

`length` does not exist any more, thus it has nothing to do here.

But for ` - Key 'satac_localisation' was not defined. Path: '/vars/checker/defaults'.` I am more in doubt... This used to be a "home made" checker, thus how am I supposed to define such specific checkers in version 2 ?

**Comment by kalbermattenm** [comment]
By the way, is `length`really deprecated in the shortner, because it is still in the doc https://camptocamp.github.io/c2cgeoportal/master/integrator/shortener.html ?

**Comment by sbrunner** [comment]
For `satac_localisation` I will provide something to make it possible ...

**Comment by sbrunner** [comment]
No it isn't ...

**Comment by kalbermattenm** [comment]
OK, thanks, in the mean time, I will edit `CONST_config-schema.yaml` in order for this step not to be a blocker ;-)

**Comment by sbrunner** [comment]
Yes, you can try this :-)
https://github.com/camptocamp/c2cgeoportal/compare/config-check
