### ISSUE TITLE
Error installing 2.2.0rc3

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#2992]
When installing 2.2.0rc3, II get the following error on step 4
```
.build/venv/bin/c2c-template --vars vars_cartoriviera.yaml --get-config .build/_config.yaml lidar_http lidar_https targetemail servicesenderemail emailhost ogcproxy_enable instanceid sqlalchemy.url schema parentschema enable_admin_interface pyramid_closure node_modules_path closure_library_path default_locale_name servers layers available_locale_names cache admin_interface functionalities external_themes_url raster shortener hide_capabilities mapserverproxy tinyowsproxy resourceproxy print_url tiles_url checker check_collector default_max_age jsbuild package srid reset_password fulltextsearch headers authorized_referers hooks stats db_chooser ogcproxy_enable dbsessions urllogin host_forward_host
.build/venv/bin/pykwalify --data-file .build/_config.yaml --schema-file CONST_config-schema.yaml
 ERROR - validation.invalid
 ERROR -  --- All found errors ---
 ERROR - [u"Key 'query' was not defined. Path: '/vars/checker/all/phantomjs_routes/0'", u"Key 'query' was not defined. Path: '/vars/checker/all/phantomjs_routes/1'", u"Value '10000' is not a dict. Value path: '/vars/checker/print_scale'", u"Value '['cgxp']' is not a dict. Value path: '/vars/checker/lang_files'", u"Value '1) A4 portrait' is not a dict. Value path: '/vars/checker/print_template'", u"Value '554302' is not a dict. Value path: '/vars/checker/print_center_lon'", u"Key 'query' was not defined. Path: '/vars/checker/defaults/phantomjs_routes/0'", u"Value '145654' is not a dict. Value path: '/vars/checker/print_center_lat'"]
Traceback (most recent call last):
  File ".build/venv/bin/pykwalify", line 11, in <module>
    sys.exit(cli_entrypoint())
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/pykwalify/cli.py", line 95, in cli_entrypoint
    run(parse_cli())
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/pykwalify/cli.py", line 82, in run
    c.validate()
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/pykwalify/core.py", line 176, in validate
    error_msg=u'.\n - '.join(self.validation_errors)))
pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
 - Key 'query' was not defined. Path: '/vars/checker/all/phantomjs_routes/0'.
 - Key 'query' was not defined. Path: '/vars/checker/all/phantomjs_routes/1'.
 - Value '10000' is not a dict. Value path: '/vars/checker/print_scale'.
 - Value '['cgxp']' is not a dict. Value path: '/vars/checker/lang_files'.
 - Value '1) A4 portrait' is not a dict. Value path: '/vars/checker/print_template'.
 - Value '554302' is not a dict. Value path: '/vars/checker/print_center_lon'.
 - Key 'query' was not defined. Path: '/vars/checker/defaults/phantomjs_routes/0'.
 - Value '145654' is not a dict. Value path: '/vars/checker/print_center_lat'.: Path: '/'>
CONST_Makefile:686: recipe for target '.build/config.yaml' failed
make[1]: *** [.build/config.yaml] Error 1
make[1]: Leaving directory '/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish'
```

**Comment by kalbermattenm** [comment]
See https://github.com/camptocamp/c2cgeoportal/issues/2986

**Comment by gnerred** [comment]
Ok, I'll wait the next RC :-/ ...

**Comment by sbrunner** [comment]
It's already in the rc3...

**Comment by gnerred** [comment]
So what is the problem ?

**Comment by gnerred** [comment]
And what to do ?

**Comment by sbrunner** [comment]
- Key 'query' was not defined. Path: '/vars/checker/all/phantomjs_routes/0'.
 - Key 'query' was not defined. Path: '/vars/checker/all/phantomjs_routes/1'.

missing query... https://github.com/camptocamp/demo_geomapfish/blob/master/CONST_vars.yaml#L356-L357

 - Value '10000' is not a dict. Value path: '/vars/checker/print_scale'.
 - Value '['cgxp']' is not a dict. Value path: '/vars/checker/lang_files'.
 - Value '1) A4 portrait' is not a dict. Value path: '/vars/checker/print_template'.
 - Value '554302' is not a dict. Value path: '/vars/checker/print_center_lon'.

The display of error is not evident, but it should be in /vars/checker/defaults/...

 - Key 'query' was not defined. Path: '/vars/checker/defaults/phantomjs_routes/0'.

same first

 - Value '145654' is not a dict. Value path: '/vars/checker/print_center_lat'.: Path: '

same second

**Comment by gnerred** [comment]
@sbrunner , this message is for me or intern for bugfix... ?

**Comment by sbrunner** [comment]
It's for you :-)

**Comment by gnerred** [comment]
Ok thanks for informations given by phone ;-)
