### ISSUE TITLE
Problem running script themev1tov2

### ISSUE THREAD

**Issue by gnerred** [camptocamp/c2cgeoportal#3001]
Version 2.2.0rc2

When running script .build/venv/bin/themev1tov2, I get the following error. What is the problem ? 

Emptying table main.layer_wmts.
Emptying table main.layer_wms.
Emptying table main.ogc_server.
Converting layerv1.
Traceback (most recent call last):
  File ".build/venv/bin/themev1tov2", line 11, in <module>
    sys.exit(main())
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/themev1tov2.py", line 103, in main
    layer_v1tov2(session, layer)
  File "/var/www/vhosts/cartoriviera_preprod/private/cartoriviera_geomapfish/.build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/themev1tov2.py", line 218, in layer_v1tov2
    new_link.group = link.group
AttributeError: 'LayergroupTreeitem' object has no attribute 'group'

**Comment by ger-benjamin** [comment]
Thanks @gnerred . I've opened a PR. That will be in the rc3

**Comment by gnerred** [comment]
Thanks @ger-benjamin . You mean rc4 ?

**Comment by ger-benjamin** [comment]
Yes, sorry, rc4.
