### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/c2cgeoportal#3010]
```
Traceback (most recent call last):
  File ".build/venv/bin/pot-create", line 11, in <module>
    sys.exit(main())
  File "/var/www/vhosts/geomapfish-demo/private/2.2/.build/venv/local/lib/python2.7/site-packages/lingua/extract.py", line 307, in main
    register_extractors()
  File "/var/www/vhosts/geomapfish-demo/private/2.2/.build/venv/local/lib/python2.7/site-packages/lingua/extractors/__init__.py", line 152, in register_extractors
    extractor = entry_point.load(require=True)
  File "/var/www/vhosts/geomapfish-demo/private/2.2/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    self.require(*args, **kwargs)
  File "/var/www/vhosts/geomapfish-demo/private/2.2/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2325, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/var/www/vhosts/geomapfish-demo/private/2.2/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 860, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pyramid 1.9.1 (/var/www/vhosts/geomapfish-demo/private/2.2/.build/venv/lib/python2.7/site-packages), Requirement.parse('pyramid<=1.8.99'))
CONST_Makefile:717: recipe for target 'demo/locale/demo-client.pot' failed
```

**Comment by sbrunner** [comment]
Unable to reproduce :-/
