### ISSUE TITLE
2.2.0rc5 - Pot generation error

### ISSUE THREAD

**Issue by kalbermattenm** [camptocamp/c2cgeoportal#3043]
I get an error when building the application and when there is a layer in the DB which is not defined in the mapfile, see here under.

@sbrunner, I remember having had that error in the past and that you implemented some kind of a workaround, but I could not retrieve the related GitHub issue. This workaround still used to work with version 2.2.0rc2.

This is **not a blocker** (I deleted the layers in the DB...), this is to inform you that the implemented workaround is not working anymore.

```
Get WFS DescribeFeatureType for URL: http://localhost/michael/mapserv?VERSION=1.1.0&REQUEST=DescribeFeatureType&SERVICE=WFS
[01;31mERROR! No such table 'agriculture.ag15_perimetres_cultures' for layer 'ag15_perimetres_cultures'.[0m
[01;31mTraceback (most recent call last):
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\lingua_extractor.py", line 357, in _import_layer_wms
    cls = get_class(layer.geo_table, exclude_properties=exclude)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\dbreflection.py", line 189, in get_class
    table = get_table(tablename, schema, session)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\dbreflection.py", line 168, in get_table
    autoload_with=engine,
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 439, in __new__
    metadata._remove_table(name, schema)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 434, in __new__
    table._init(name, metadata, *args, **kw)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 514, in _init
    include_columns, _extend_on=_extend_on)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 527, in _autoload
    _extend_on=_extend_on
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2045, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1534, in run_callable
    return callable_(self, *args, **kwargs)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\default.py", line 372, in reflecttable
    table, include_columns, exclude_columns, **opts)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 598, in reflecttable
    table_name, schema, **table.dialect_kwargs):
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 369, in get_columns
    **kw)
  File "<string>", line 2, in get_columns
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\dialects\postgresql\base.py", line 2414, in get_columns
    info_cache=kw.get('info_cache'))
  File "<string>", line 2, in get_table_oid
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\dialects\postgresql\base.py", line 2340, in get_table_oid
    raise exc.NoSuchTableError(table_name)
NoSuchTableError: ag15_perimetres_cultures
[0m
[01;31mERROR! The schema didn't seem to exists (should be ignored when happen during the deploy)[0m
[01;31mag15_perimetres_cultures[0m
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\git_projects\sitn_c2cgeoportal\.build\venv\Scripts\pot-create.exe\__main__.py", line 9, in <module>
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\lingua\extract.py", line 336, in main
    for message in extractor(real_filename, options):
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\lingua_extractor.py", line 288, in __call__
    self._import(LayerWMS, messages, self._import_layer_wms)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\lingua_extractor.py", line 339, in _import
    callback(item, messages)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\lingua_extractor.py", line 357, in _import_layer_wms
    cls = get_class(layer.geo_table, exclude_properties=exclude)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\dbreflection.py", line 189, in get_class
    table = get_table(tablename, schema, session)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\c2cgeoportal\lib\dbreflection.py", line 168, in get_table
    autoload_with=engine,
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 439, in __new__
    metadata._remove_table(name, schema)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 434, in __new__
    table._init(name, metadata, *args, **kw)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 514, in _init
    include_columns, _extend_on=_extend_on)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 527, in _autoload
    _extend_on=_extend_on
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2045, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1534, in run_callable
    return callable_(self, *args, **kwargs)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\default.py", line 372, in reflecttable
    table, include_columns, exclude_columns, **opts)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 598, in reflecttable
    table_name, schema, **table.dialect_kwargs):
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 369, in get_columns
    **kw)
  File "<string>", line 2, in get_columns
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\dialects\postgresql\base.py", line 2414, in get_columns
    info_cache=kw.get('info_cache'))
  File "<string>", line 2, in get_table_oid
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "c:\git_projects\sitn_c2cgeoportal\.build\venv\lib\site-packages\sqlalchemy\dialects\postgresql\base.py", line 2340, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: ag15_perimetres_cultures
make: *** [CONST_Makefile:723: sitn/locale/sitn-client.pot] Error 1
```

**Comment by sbrunner** [comment]
I see:
```
...
No such table 'agriculture.ag15_perimetres_cultures' for layer 'ag15_perimetres_cultures'.
...
The schema didn't seem to exists (should be ignored when happen during the deploy)
... 
```
You should probably know what is it :-)

**Comment by kalbermattenm** [comment]
Yes I know that my DB is not clean and that some layers are missing. But with the previous version, these missing layers did not make the process to fail. It was emitted as a warning, not generating an error which stop the build process.

**Comment by sbrunner** [comment]
Yes, we change that because it was too hidden...

**Comment by kalbermattenm** [comment]
Ah.... then I suppose that I will have to be careful ;-)
