### ISSUE TITLE
FileNotFoundError: /opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scaffolds/update

### ISSUE THREAD

**Issue by fvanderbiest** [camptocamp/c2cgeoportal#3314]
eg on https://github.com/camptocamp/c2cgeoportal/pull/3311 

-> https://ci.camptocamp.com/blue/organizations/jenkins/geospatial%2Fc2cgeoportal/detail/fixreadme/1/pipeline KO with

```
Continue with:
SRID=21781 EXTENT=489246.36,78873.44,837119.76,296543.14 ./docker-run pcreate --scaffold c2cgeoportal_update --ignore-conflicting-name --package-name testgeomapfish ../testgeomapfish
+ ./docker-run --image=camptocamp/geomapfish-build --share /tmp/travis pcreate --scaffold=c2cgeoportal_update /home/jenkins-slave/workspace/testgeomapfish --ignore-conflicting-name --package-name testgeomapfish
groupadd: GID '0' already exists
useradd: user 'root' already exists
Note: As of Pyramid 1.8, this command is deprecated. Use a specific
cookiecutter instead:
https://github.com/pylons/?query=cookiecutter

Traceback (most recent call last):
  File "/usr/local/bin/pcreate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pyramid/scripts/pcreate.py", line 19, in main
    return command.run()
  File "/usr/local/lib/python3.6/site-packages/pyramid/scripts/pcreate.py", line 114, in run
    return self.render_scaffolds()
  File "/usr/local/lib/python3.6/site-packages/pyramid/scripts/pcreate.py", line 164, in render_scaffolds
    scaffold.run(self, output_dir, props)
  File "/usr/local/lib/python3.6/site-packages/pyramid/scaffolds/template.py", line 65, in run
    self.write_files(command, output_dir, vars)
  File "/usr/local/lib/python3.6/site-packages/pyramid/scaffolds/template.py", line 97, in write_files
    template_renderer=self.render_template,
  File "/usr/local/lib/python3.6/site-packages/pyramid/scaffolds/copydir.py", line 64, in copy_dir
    names = sorted(os.listdir(source))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scaffolds/update'
script returned exit code 2
```

**Comment by fvanderbiest** [comment]
Issue did not show up anymore, but now we have
```
[tial_c2cgeoportal_fixreadme-IKLGWELZWKNXDCV2OEDW7DYB3CA5VJ6HQ2VI6J2CRNHQXN5H6JOA] Running shell script
+ travis/run-on.sh /home/jenkins-slave/workspace/testgeomapfish/ docker-compose up -d
Pulling external-db (camptocamp/testgeomapfish-external-db:latest)...
Pulling repository docker.io/camptocamp/testgeomapfish-external-db
Error: image camptocamp/testgeomapfish-external-db:latest not found
script returned exit code 1
```
