### ISSUE TITLE
Error when creating users with manage_users script

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#3322]
* GeoMapFish version: 2.1.1

Running command: `$ .build/venv/bin/manage_users -c -r <role> -p <password> -e <email> <login>`

Result:

```
Traceback (most recent call last):
  File ".build/venv/bin/manage_users", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/manage_users.py", line 91, in main
    help="The user"
  File "/usr/lib/python2.7/argparse.py", line 1306, in add_argument
    raise ValueError("length of metavar tuple does not match nargs")
ValueError: length of metavar tuple does not match nargs
```

It was working in 1.6.

**Comment by rbovard** [comment]
@sbrunner Any news on this one?

**Comment by ybolognini** [comment]
Done
