### ISSUE TITLE
upgrade to 2.3: error handling in upgrade script not working

### ISSUE THREAD

**Issue by jwkaltz** [camptocamp/c2cgeoportal#3704]
If you do not have have a section "managed_files" in the project.yaml.mako, or if there is no entry in the section "managed_files", the error handling of c2cupgrade.py does not work:

```
./docker-run --home --image=camptocamp/geomapfish-build --version=2.3.0.dev13 c2cupgrade --nondocker --makefile=wkaltz23.mk --new-makefile=wkaltz23.mk --step=1

Traceback (most recent call last):
  File "/usr/local/bin/c2cupgrade", line 11, in <module>
    load_entry_point('c2cgeoportal-geoportal', 'console_scripts', 'c2cupgrade')()
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 87, in main
    c2cupgradetool.upgrade()
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 276, in upgrade
    self.run_step(self.options.step)
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 242, in run_step
    getattr(self, "step{}".format(step))()
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 148, in decorate
    current_step(c2cupgradetool, self.step_number, *args, **kwargs)
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 331, in step1
    self.run_step(step + 1)
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 242, in run_step
    getattr(self, "step{}".format(step))()
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 148, in decorate
    current_step(c2cupgradetool, self.step_number, *args, **kwargs)
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 359, in step2
    self.run_step(step + 1)
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 242, in run_step
    getattr(self, "step{}".format(step))()
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 148, in decorate
    current_step(c2cupgradetool, self.step_number, *args, **kwargs)
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 384, in step3
    self.run_step(step + 1)
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 242, in run_step
    getattr(self, "step{}".format(step))()
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 148, in decorate
    current_step(c2cupgradetool, self.step_number, *args, **kwargs)
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 391, in step4
    error |= self.files_to_remove(pre=True)
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 431, in files_to_remove
    for pattern in self.project["managed_files"]:
KeyError: 'managed_files'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 169, in message
    message="The step get an error '{}'.".format(e),  # noqa: F821
NameError: free variable 'e' referenced before assignment in enclosing scope
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 169, in message
    message="The step get an error '{}'.".format(e),  # noqa: F821
NameError: free variable 'e' referenced before assignment in enclosing scope
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 169, in message
    message="The step get an error '{}'.".format(e),  # noqa: F821
NameError: free variable 'e' referenced before assignment in enclosing scope
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/c2cgeoportal_geoportal/c2cgeoportal_geoportal/scripts/c2cupgrade.py", line 169, in message
    message="The step get an error '{}'.".format(e),  # noqa: F821
NameError: free variable 'e' referenced before assignment in enclosing scope
```

**Comment by jwkaltz** [comment]
I think this is fixed by https://github.com/camptocamp/c2cgeoportal/pull/3703

**Comment by sbrunner** [comment]
Partially ...
