### ISSUE TITLE
WMTS dimensions is broken if value is an integer

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#3881]
Project:

* GitHub URL: https://github.com/camptocamp/nyon_c2cgeoportal
* GeoMapFish version: 2.2.4

When adding an WMTS v1 layer with an integer as dimensions, the generated query translate the value to `undefined`:

* Dimensions: `2015`
* Query: `https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/undefined/21781/28/8296/3381.jpeg`

I think there is an issue with integer values because when trying to convert layers to v2, I have this error:

```
Converting layerv1.
Traceback (most recent call last):
  File ".build/venv/bin/themev1tov2", line 11, in <module>
    sys.exit(main())
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/themev1tov2.py", line 104, in main
    layer_v1tov2(session, layer)
  File ".build/venv/local/lib/python2.7/site-packages/c2cgeoportal/scripts/themev1tov2.py", line 237, in layer_v1tov2
    for name, value in dimensions.items():
AttributeError: 'int' object has no attribute 'items'
```

**Comment by rbovard** [comment]
Solved by quoting value: `"2015"`

**Comment by sbrunner** [comment]
+1 It's the right way to do it :-)
